### ISSUE TITLE
Installation issues? could not find application file: language_server.app

### ISSUE THREAD

**Issue by jeremyjh** [JakeBecker/vscode-elixir-ls#1]
Does the language server need to be installed independently of the plugin? I installed the ElixirLS plugin in Visual Studio code but this yields only errors such as:

```
** (Mix) Could not start application language_server: could not find application file: language_server.app
[Info  - 7:48:04 AM] Connection to server got closed. Server will restart.
```

**Comment by JakeBecker** [comment]
Ah, I think this error happens when you use Elixir 1.3. Can you confirm which Elixir version you're using? I'm working on a fix.

**Comment by jeremyjh** [comment]
I'm using 1.4.4.

**Comment by JakeBecker** [comment]
@jeremyjh I believe I've fixed it. Could you update to 0.0.4 and let me know? Thank you!

**Comment by jeremyjh** [comment]
That did fix it, thanks!
