### ISSUE TITLE
The ElixirLS server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by Parangon** [JakeBecker/vscode-elixir-ls#10]
Thanks for this extension, however I couldn't use it and always got the following output 

**Connection to server got closed. Server will restart.
'C:\Users\Fabien' n'est pas reconnu en tant que commande interne**

sorry it's in french :) but the last line means => C:\Users\Fabien' is not recognized as an internal or external command

the extension is installed under my user directory 'C:\Users\FirstName LastName\ .vscode\extensions\...' 

it seems like the language server cannot be started when there is a space in the path. 

I made it works with an other user account without space in the username

**Comment by JakeBecker** [comment]
Should be fixed now. Thanks for reporting, and sorry for the wait!

**Comment by Parangon** [comment]
Thank you !
