### ISSUE TITLE
add option to start bash in interactive mode

### ISSUE THREAD

**Issue by olivermt** [JakeBecker/vscode-elixir-ls#100]
Hi.  Could you add to the settings that the language server is started with -i ? (and maybe make it default?)

On linux the default is to not run the bashrc if not in interactive mode, so a lot of people using vscode won't have this work unless they open terminal and then `code .` instead of opening vscode from the GUI.

I've been reading a lot of issues from other people using vscode and it doesn't seem like resourcing bash is ever a problem for task runing, which you can certainly claim running the LS is.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
