### ISSUE TITLE
Disable automatically inserting @spec on functions?

### ISSUE THREAD

**Issue by nathanchere** [JakeBecker/vscode-elixir-ls#101]
As per title. I can't find any mention of how to disable this in configuration, and it is extremely annoying to keep having @spec lines added to functions which flood code with warnings. Can it be disabled somehow?

**Comment by nathanchere** [comment]
Also a way of preventing @spec lines from being formatted like code lens annotations?

**Comment by bobics** [comment]
I think you want
```
"elixirLS.suggestSpecs": false
```
In your `settings.json` / VSCode extension settings UI.

**Comment by nathanchere** [comment]
That's great, thanks. I also found it's possible to turn off 'code lens' entirely with `"editor.codeLens": false`, hallelujah!
