### ISSUE TITLE
Missing Git GUI overlay on merge conflicts

### ISSUE THREAD

**Issue by dev-cyprium** [JakeBecker/vscode-elixir-ls#102]
## Problem with the git conflicts in files

I got a merge conflict with git, and the usual buttons that appear ( accept incoming, accept mine, etc. ) were missing. My primary suspect was **Elixir LS** since it added support for automatic type suggestions. 

If I disable the plugin, I got the conflict toolbar rendering again.

Edit:
I've mentioned it only happens in the Phoenix router, but I got a conflict in one of the files as well, and the text for resolving conflicts did not show up until I've disabled the `suggestSpecs` option.

**Comment by cdfuller** [comment]
For anybody interested, this feature can be disabled without disabling the entire plugin.

`"elixirLS.suggestSpecs": false`

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
