### ISSUE TITLE
no match of right hand side :error

### ISSUE THREAD

**Issue by qqdanielqq** [JakeBecker/vscode-elixir-ls#103]
When opening a project in `vs-code` it will compile before checking for stale files, while doing so it will throw this error:
```
[Error - 13:37:35] Process #PID<0.12827.1> raised an exception
** (MatchError) no match of right hand side value: :error
    erl_types.erl:4798: :erl_types.type_from_form/6
    erl_types.erl:5347: :erl_types.t_form_to_string/1
    erl_types.erl:5300: :erl_types.t_form_to_string/1
    erl_types.erl:5362: :erl_types.t_form_to_string_list/2
    erl_types.erl:5359: :erl_types.t_form_to_string/1
    dialyzer_contracts.erl:103: :dialyzer_contracts.contract_to_string_1/1
    dialyzer_contracts.erl:804: :dialyzer_contracts.extra_contract_warning/6
    dialyzer_contracts.erl:787: :dialyzer_contracts.picky_contract_check/7
[Error - 13:37:35] Child ElixirLS.LanguageServer.Dialyzer of Supervisor #PID<0.103.0> (ElixirLS.LanguageServer.Dialyzer.Supervisor) terminated
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        erl_types.erl:4798: :erl_types.type_from_form/6
        erl_types.erl:5347: :erl_types.t_form_to_string/1
        erl_types.erl:5300: :erl_types.t_form_to_string/1
        erl_types.erl:5362: :erl_types.t_form_to_string_list/2
        erl_types.erl:5359: :erl_types.t_form_to_string/1
        dialyzer_contracts.erl:103: :dialyzer_contracts.contract_to_string_1/1
        dialyzer_contracts.erl:804: :dialyzer_contracts.extra_contract_warning/6
        dialyzer_contracts.erl:787: :dialyzer_contracts.picky_contract_check/7
Pid: #PID<0.104.0>
Start Call: ElixirLS.LanguageServer.Dialyzer.start_link({#PID<0.101.0>, 
```

The version being used currently is:
```
Erlang/OTP 20 [erts-9.3.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.5 (compiled with OTP 20)
```

Steps to reproduce: 
* Open a project
* Watch it compile
* Will throw this error during the step of `checking for stale files`

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
