### ISSUE TITLE
VS Code 1.27.1 startup :: The ElixirLS server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by jsimmonds2** [JakeBecker/vscode-elixir-ls#104]
Screen grab (Ubuntu 18.04.1 64-bit on Intel)
![screenshot from 2018-09-07 19-13-09](https://user-images.githubusercontent.com/1224439/45210597-6230a980-b2d3-11e8-9375-4924b984c44f.png)

**Comment by delameko** [comment]
Go to the View menu > Output

Then select ElixirLS from the dropdown on the right, that'll tell you what's wrong.

**Comment by jsimmonds2** [comment]
Thanks for that prompting . . here we are :+1: 
`16:22:35.036 [error] GenServer ElixirLS.LanguageServer.Server terminating
** (UndefinedFunctionError) function :dialyzer_utils.get_core_from_beam/1 is undefined (module :dialyzer_utils is not available)
    :dialyzer_utils.get_core_from_beam('/usr/local/lib/elixir/bin/../lib/elixir/ebin/Elixir.System.beam')
    (language_server) lib/language_server/dialyzer/utils.ex:6: ElixirLS.LanguageServer.Dialyzer.Utils.dialyzable?/1
    (language_server) lib/language_server/dialyzer.ex:35: ElixirLS.LanguageServer.Dialyzer.check_support/0
    (language_server) lib/language_server/server.ex:563: ElixirLS.LanguageServer.Server.show_version_warnings/0
    (language_server) lib/language_server/server.ex:294: ElixirLS.LanguageServer.Server.handle_request/2
    (language_server) lib/language_server/server.ex:127: ElixirLS.LanguageServer.Server.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
Last message: {:"$gen_cast", {:receive_packet, %{"id" => 0, "jsonrpc" => "2.0", "method" => "initialize", "params" => %{"capabilities" => %{"textDocument" => %{"codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dynamicRegistration" => true}, "codeLens" => %{"dynamicRegistration" => true}, "colorProvider" => %{"dynamicRegistration" => true}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => true, "deprecatedSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "preselectSupport" => true, "snippetSupport" => true}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "contextSupport" => true, "dynamicRegistration" => true}, "definition" => %{"dynamicRegistration" => true}, "documentHighlight" => %{"dynamicRegistration" => true}, "documentLink" => %{"dynamicRegistration" => true}, "documentSymbol" => %{"dynamicRegistration" => true, "hierarchicalDocumentSymbolSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "foldingRange" => %{"dynamicRegistration" => true, "lineFoldingOnly" => true, "rangeLimit" => 5000}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => true}, "implementation" => %{"dynamicRegistration" => true}, "onTypeFormatting" => %{"dynamicRegistration" => true}, "publishDiagnostics" => %{"relatedInformation" => true}, "rangeFormatting" => %{"dynamicRegistration" => true}, "references" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true}, "signatureHelp" => %{"dynamicRegistration" => true, "signatureInformation" => %{"documentationFormat" => ["markdown", "plaintext"]}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"dynamicRegistration" => true}}, "workspace" => %{"applyEdit" => true, "configuration" => true, "didChangeConfiguration" => %{"dynamicRegistration" => true}, "didChangeWatchedFiles" => %{"dynamicRegistration" => true}, "executeCommand" => %{"dynamicRegistration" => true}, "symbol" => %{"dynamicRegistration" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, "workspaceEdit" => %{"documentChanges" => true}, "workspaceFolders" => true}}, "processId" => 5699, "rootPath" => nil, "rootUri" => nil, "trace" => "off", "workspaceFolders" => []}}}}
State: %ElixirLS.LanguageServer.Server{analysis_ready?: false, awaiting_contracts: [], build_diagnostics: [], build_ref: nil, build_running?: false, client_capabilities: nil, dialyzer_diagnostics: [], dialyzer_sup: nil, needs_build?: false, project_dir: nil, received_shutdown?: false, requests: %{}, root_uri: nil, settings: nil, source_files: %{}}`

**Comment by delameko** [comment]
What version of Erlang/Elixir are you running?

    elixir -v

If you open an `iex` session in the terminal and type `h :dialyzer_utils.get_core_from_beam/1`, what's the result?

Are you opening vscode directly, or from the terminal?  If you open it from the terminal with `code . `, do you still get the same error?

**Comment by jsimmonds2** [comment]
Thanks for your interest.  More details for platform and Elixir ->

`$ uname -srvi
Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64
$ cat /etc/issue.net 
Ubuntu 18.04.1 LTS

$ elixir --version
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.7.3 (compiled with Erlang/OTP 19)

iex(1)> h :dialyzer_utils.get_core_from_beam/1
Could not load module :dialyzer_utils, got: nofile
iex(2)> 
`
Am using Ubuntu desktop GUI to start VS Code from icon.   Using terminal and starting with `code` has same result.
Looks like I've dropped dialyzer somewhere along the way.
I've been using the official ESL releases for Ubuntu (bionic) via `apt-get`

**Comment by delameko** [comment]
I'm on Mac, so I just let homebrew install it for me.

I think you might just have to install the `erlang-dialyzer` package.  However, did you install `erlang` or `esl-erlang`, I think esl-erlang includes all the additional packages.

On my Ubuntu build server, I have installed `erlang erlang-base-hipe erlang-dev erlang-parsetools erlang-xmerl elixir`.  But its been a few years since I set that up, and I don't remember the rational for those choices.  I did just log into it, and :dialyzer_utils is present.

**Comment by jsimmonds2** [comment]
Thanks.  We're getting much closer :)

I had installed plain `erlang` packages required to get Elixir working.
Installed `erlang-dialyzer` just now as you suggested but now it seems the 1.7.3 Precompiled from elixir-lang/elixir on GitHub don't have debug info.   Looking like I'll have to build Elixir from source (??)

![image](https://user-images.githubusercontent.com/1224439/45534737-6dd62000-b83f-11e8-99b4-454edab2cb10.png)

**Comment by Douuuglas** [comment]
I had this problem on Fedora 32 with VS Code. It's really the erlang-dialyzer missing, so i did an "sudo dnf install erlang" and got everything working!

**Comment by girorme** [comment]
> I had this problem on Fedora 32 with VS Code. It's really the erlang-dialyzer missing, so i did an "sudo dnf install erlang" and got everything working!

Using `apt get install erlang` in Ubuntu 20.04.1 resolved the issue too.

**Comment by frunox** [comment]
I am having the same problem - the ElixirLS server crashes.  I just installed VS Code and ElixirLS.

The output says "ElixirLS compiled with Elixir 1.10.4 and erlang 22".   I just installed Elixir, and it's version 1.12.3.  Is this a problem?

I opened iex and ran "h :dialyzer_utils.get_core_from_beam/1"  and got a response.

**Comment by fschoenfeldt** [comment]
For me, the Elixir LS only crashes the first time I do a clean boot of my system. I then close VSCode and fire it up again, it then always work. 

Also:
```zsh
➜  ~ elixir -v
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 24)

---

iex(3)> h :dialyzer_utils
:dialyzer_utils was not compiled with docs
```

I'm using the asdf version of elixir.
