### ISSUE TITLE
Have some problem when use debug

### ISSUE THREAD

**Issue by tlatforlz** [JakeBecker/vscode-elixir-ls#105]
My configuration (launch.json) : 
```
        {
            "type": "mix_task",
            "name": "start phoenix",
            "request": "launch",
            "projectDir": "${workspaceRoot}",
            "task": "phx.server"
        }
```
But I got a error
```
(Debugger) Initialization failed because an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :on_load_failure}
        int.erl:531: anonymous fn/3 in :int.load/2
        int.erl:527: :int.load/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (debugger) lib/debugger/server.ex:469: ElixirLS.Debugger.Server.initialize/1
```
Is there have other config in launch.json or config in project?

**Comment by tlatforlz** [comment]
Is any update for this :)

**Comment by jefflafay** [comment]
I'm getting the same thing.

**Comment by tlatforlz** [comment]
@jefflafay haha, I give up it.

**Comment by leandrocp** [comment]
@tlatforlz and @jefflafay that's the whole message ?
The fix from https://github.com/JakeBecker/vscode-elixir-ls/issues/25 worked for me, but maybe it's a different problem.

**Comment by tlvenn** [comment]
This is indeed the whole error:

```
Started ElixirLS debugger
Elixir version: "1.8.2 (compiled with Erlang/OTP 21)"
Erlang version: "21"
(Debugger) Initialization failed because an exception was raised:
    ** (MatchError) no match of right hand side value: false
        int.erl:542: anonymous fn/1 in :int.load/2
        int.erl:540: :int.load/2
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
        (debugger) lib/debugger/server.ex:473: ElixirLS.Debugger.Server.initialize/1
```

Any idea what is going on ?

**Comment by marknuzz-itk** [comment]
Getting the same problem.

**Comment by mz2** [comment]
Same here…

**Comment by tiger808** [comment]
Hmmm... that looks like what you see when it fails on loading a nif. Does your project use nif? If so then you need to exclude those modules in the launch config:
`”excludeModules”: [“My.Nif1”, ”My.Nif2”]`

**Comment by aJunKobayashi** [comment]
This issue occurs due to exception from :int.ni() in elixir-ls.
:int.ni() cannot load some modules
I create PR to fix this issue.
https://github.com/JakeBecker/elixir-ls/pull/202

If this PR is merged, this issue will be fixed.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
