### ISSUE TITLE
Support *.eex syntaxes

### ISSUE THREAD

**Issue by ejpcmac** [JakeBecker/vscode-elixir-ls#106]
Currently, only raw *EEx* and *HTML (EEx)* syntaxes are supported. There is potentially a very large number of possibilities. To name a few:

* *Markdown (EEx)* => `.md.eex`
* *Elixir (EEx)* => `.ex.eex` / `.exs.eex`
* *Nix (EEx)* => `.nix.eex`
* Any other `*.eex`

It can be useful to support any EEx format, especially when writing templates for project generators. I’m not sure however if VSCode can manage a `*.eex` format.

**Comment by thiagomajesk** [comment]
+1

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
