### ISSUE TITLE
Problem with new line added at end of the file when save it

### ISSUE THREAD

**Issue by DarckBlezzer** [JakeBecker/vscode-elixir-ls#107]
I have a issue with a new line added when I save the file

"files.insertFinalNewline": false,

I have added the config to user config and work space config and the extension doesn't respect it...

I know that is the extension because I try disable it and test and then enable and test again.

**Comment by whatyouhide** [comment]
Are you by any chance also formatting code when saving with the Elixir formatter? Because the Elixir formatter also adds a final newline.

**Comment by JakeBecker** [comment]
^ This is most likely what's happening. You may have `"editor.formatOnSave": true` set. Try setting it to `false` and see if that fixes it. I recommend leaving the final newline, though, since the formatter will add it anyway.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
