### ISSUE TITLE
Unable to locate the "go to definition" option

### ISSUE THREAD

**Issue by the-shank** [JakeBecker/vscode-elixir-ls#11]
As the title says, I am unable to locate how to use the "go to definition" feature of the extension.

**Comment by JakeBecker** [comment]
Documented here: https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

The default keyboard shortcut seems to be the intuitive and common-sense `F12`. I changed mine to `Cmd + B`.

Btw, I just pushed some bug fixes, so make sure you update your extension in case that was a problem. Thanks!
