### ISSUE TITLE
Navigate to Module via command + click?

### ISSUE THREAD

**Issue by dschinkel** [JakeBecker/vscode-elixir-ls#110]
Is there any functionality to command + click to navigate to types like you can in IntelliJ?  I don't see that ability enabling this  plugin.  I don't see that ability in any of the plugins period in VSCode for Elixir which is a shame.

**Comment by quolpr** [comment]
@dschinkel if you think that it is a shame - you can provide the Pull Request 😊

**Comment by chulkilee** [comment]
What's missing here? Navigating to module via command + click works (0.2.25).

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
