### ISSUE TITLE
Console option for launch.json file

### ISSUE THREAD

**Issue by phpcitizen** [JakeBecker/vscode-elixir-ls#112]
Would there be an option to change/add console argument launch.json debug configuration file, so we can add WSL as the console in debug.

**Comment by jakeprem** [comment]
I've been exploring this a little bit.

You can invoke WSL from a Windows Command Prompt with `wsl <command>`. So I think a setting could be added that would change the Elixir commands from `elixir <args>` to `wsl elixir <args>`

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
