### ISSUE TITLE
Extension disables all vscode color themes

### ISSUE THREAD

**Issue by Marcos-Amazonas** [JakeBecker/vscode-elixir-ls#113]
## My Setup
I have installed Erlang and Elixir with asdf versioner, and I have installed the phoenix framework.
After that I've created a phoenix project and that's all.

OS: Linux Ubuntu 18.04
vscode: 1.28.2.
ElixirLs: ELixir Suport and debugger: 0.2.24
Color theme Monokai.

Erlang: OTP 21.1
ELixir: 1.7.3

## My Problem
After I've installed the extension whenever I disable it or unninstall it I loose the color themes for elixir files, by the way I'm not using any extension for color themes.

![captura de tela de 2018-10-26 15-50-39](https://user-images.githubusercontent.com/32882829/47587724-36788a00-d93a-11e8-8fbf-f23a5bbb38b6.png)
![captura de tela de 2018-10-26 15-51-04](https://user-images.githubusercontent.com/32882829/47587727-3b3d3e00-d93a-11e8-8d95-c868bd1ab841.png)

**Comment by delameko** [comment]
ElixirLS includes syntax highlighting for Elixir files.  So if you disable it, you'll lose syntax highlighting in Elixir files.

If you still want syntax highlighting then you'll either need to re-enable the extension, or install another Elixir syntax extension.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
