### ISSUE TITLE
"go to definition" fails on nested bracketed alias (e.g. ModuleA.{ModuleB.ModuleC})

### ISSUE THREAD

**Issue by TheFirstAvenger** [JakeBecker/vscode-elixir-ls#114]
With this alias:
```
  alias ModuleA.{
    ModuleB,
    ModuleB.ModuleC,
    ModuleB.ModuleD
  }
```
"go to definition" (cmd-click/F12) on `ModuleC` or `ModuleD` works in the alias, but not in the actual code. Can't cmd-click the modules or any of their functions.

**Comment by chulkilee** [comment]
It works with vscode extension 0.2.25

**Comment by TheFirstAvenger** [comment]
Confirmed works now.

**Comment by TheFirstAvenger** [comment]
Oops, sorry it's been a while, forgot that it always worked with the alias but the problem is references where it is actually used in the code. Still doesn't work for me. @chulkilee can you confirm you are able to command-click a module that was aliased this way (e.g. cmd-click bar to go to definition):
```elixir
alias ModuleA.{ModuleB.ModuleC}

def foo do
  ModuleC.bar()
end
```

**Comment by chulkilee** [comment]
Could you reproduce with minimal but complete code?

I found one case in following code. All other reference work so I could not reproduce your case.

```
defmodule Parent.Child1 do
  defstruct [:val]
  def hello, do: :ok
end

defmodule Parent.Child2 do
  defstruct [:val]
  def hello, do: :ok
end

defmodule Tester do
  alias Parent.{Child1, Child2}

  def foo do
    Child1.hello()
    %Child2{}
  end

  def foo(%Child2{}) do
    with :ok <- Child2.hello(),
         %Child1{} <- # this struct does not work
           Child1.hello(),
         %Child1{} <- Child1.hello() do
      :ok
    end
  end
end
```


- Elixir 1.9.1
- vscode ElixirLS 0.2.25

**Comment by TheFirstAvenger** [comment]
@chulkilee the issue is not:
```elixir
  alias Parent.{Child1, Child2}
```
but
```elixir
  alias Parent.{Child.GrandChild}
```
(two levels within the curly braces)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
