### ISSUE TITLE
Code completion and go-to definition not working for alias from macro

### ISSUE THREAD

**Issue by pradosh987** [JakeBecker/vscode-elixir-ls#115]
If I alias some module in macro and use it then code completion and go-definition doesn't work. 

example:

```
defmodule App.BaseModule do
  defmacro __using__(_) do
    quote do
      alias App.{Repo, Account}, warn: false
    end
  end
end
```

```
defmodule App.Account do
  use App.BaseModule
  
  # Auto complete dosen't work in this module and go-to definition either
end


```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
