### ISSUE TITLE
is there a way to set the @spec always show instead of dynamic show?

### ISSUE THREAD

**Issue by scottming** [JakeBecker/vscode-elixir-ls#117]
The default setting is dynamic show: press cmd+1，after a while, then `@spec` show。

I do not need the delay. Is there a way to set that?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
