### ISSUE TITLE
Go to definition search continues indefinitely till the tab is closed

### ISSUE THREAD

**Issue by shmink** [JakeBecker/vscode-elixir-ls#118]
This means you get the progress bar continually moving by at the top of the window. As far as I can see there is no way to cancel other than closing the tab you're using to work on. I notice it the most when I "go to definition" on a core elixir function. Could there be a timeout or something? I don't mind it not finding the definition but the searching animation bugs me :)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
