### ISSUE TITLE
Setup instructions for elixir newbies

### ISSUE THREAD

**Issue by ChuckIrvine** [JakeBecker/vscode-elixir-ls#124]
Could you provide instruction in the readme on how to set this up? Probably, because I'm a newbie, I can't figure out how I set this up for using with my elixir project. Thanks

**Comment by seanwash** [comment]
@ChuckIrvine what do you mean by "set this up" exactly? Is there something specific that you're looking for, or is something not working how you'd expect it to?

**Comment by sjmueller** [comment]
I'm not exactly a newbie with elixir anymore, and yet I get what @ChuckIrvine is saying. The readme should have specific instructions on getting the plugin installed (easy enough), then configuring `launch.json` (not intuitive at all right now), and working with umbrella projects (there are some gotchas).

Why not make it dead simple?

**Comment by sjmueller** [comment]
Here's the problem we're having right now:
https://elixir-lang.slack.com/files/U3X8HT3H7/FKSJB1Z0W/elixirls-problem.mov

For the record, I went into the Elixir Slack community and asked for help. They seem to have zero confidence that `ElixirLS` can be used with BEAM even be used effectively with debugging and breakpoints. It was quite a disheartening discussion, because this plugin is a huge plus for those of us coming from more traditional languages.

**Comment by rickythefox** [comment]
@sjmueller same problem here. Did you get it to work?

**Comment by sjmueller** [comment]
I did not, and was laughed out of the elixir slack channel for making the argument that it’s useful to step through code and see local variable values. Not sure where to go from here.

**Comment by ChuckIrvine** [comment]
You are probably already familiar with it, but in case you aren't, this is pretty useful:

```
require IEx; IEx.pry
```

See https://elixir-lang.org/getting-started/debugging.html#iexpry0-and-iexbreak2

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
