### ISSUE TITLE
Support `envFile` in launch.json

### ISSUE THREAD

**Issue by mackeyja92** [JakeBecker/vscode-elixir-ls#126]
Other language extensions support loading environment variables from env files and it would be awesome if this extension did too!

For reference, the golang extension had a similar issue opened: https://github.com/Microsoft/vscode-go/issues/829

**Comment by velosodigital** [comment]
+1 The envFile option would make the settings.json much compact.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
