### ISSUE TITLE
Error launching Debug

### ISSUE THREAD

**Issue by davidfernandezgonzalez** [JakeBecker/vscode-elixir-ls#131]
Hi there,

while trying to launch the debug, I'm getting the following error:

Started ElixirLS debugger
Elixir version: "1.8.1 (compiled with Erlang/OTP 20)"
Erlang version: "20"
Could not find Hex, which is needed to build dependency :dialyxir

Any help?

thanks in advance

**Comment by PatrickSachs** [comment]
Try to install hex: `mix local.hex`
Or compile manually and answer "yes" to all prompts: `mix compile`

https://elixirforum.com/t/getting-started-with-phoenix-could-not-find-hex-which-is-needed-to-build-dependency-phoenix/11645

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
