### ISSUE TITLE
html.eex support

### ISSUE THREAD

**Issue by dweremeichik** [JakeBecker/vscode-elixir-ls#132]
It appears from other comments and code in this repo that there is (may be) support for "html.eex" files. However, when I create an html.eex file, I seem to have no intellisense. Additionally, it says that there is no formatter for "HTML (Eex)" installed when I attempt to format the document. 

If there is support, what logs or troubleshooting would be helpful here? If not, I suppose this would be a feature request.

In order to get partial support, I had to add the following to my settings.json:
```json
"emmet.includeLanguages": {
        "HTML (Eex)": "html"
    }
```

**Comment by arijoon** [comment]
For Formatting, they should be standard XML, so any xml formatter like Beautify are able to format the file, just add the relevant setting to treat it as html/xml.

**Comment by dweremeichik** [comment]
An update broke the previous HTML intellisense fix, you now need:
```json
"emmet.includeLanguages": {
  "HTML (EEx)": "html"
}
```
The difference is the second **E** in `EEx`.

Additionally as @arijoon stated, you can install the Beautify extension and add `"HTML (EEx)"` to the html array:
```json
"beautify.language": {
  "js": {
    "type": [
      "javascript",
      "json",
      "jsonc"
    ],
    "filename": [
      ".jshintrc",
      ".jsbeautifyrc"
    ]
  },
  "css": [
    "css",
    "less",
    "scss"
  ],
  "html": [
    "htm",
    "html",
    "HTML (EEx)"
  ]
},
```
And this will enable your HTML formatting.

This does however leave the EEx formatting and intellisense to question.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
