### ISSUE TITLE
dialyzer error with elixir 1.8.2 

### ISSUE THREAD

**Issue by broodfusion** [JakeBecker/vscode-elixir-ls#135]
```
 ~  elixir --version
Erlang/OTP 22 [erts-10.4.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.2 (compiled with Erlang/OTP 21)
```
<img src="https://user-images.githubusercontent.com/11618564/59887078-beeae580-9376-11e9-8073-a8ef070c3537.png"  />

From the output tab in vscode, I'm seeing this 
```
Info  - 4:09:54 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Error - 4:09:59 PM] Request textDocument/documentSymbol failed.
  Message: an exception was raised:
    ** (SyntaxError) nofile:45: unexpected token: end. The "{" at line 38 is missing terminator "}"
        (language_server) lib/language_server/providers/document_symbols.ex:41: ElixirLS.LanguageServer.Providers.DocumentSymbols.list_symbols/1
        (language_server) lib/language_server/providers/document_symbols.ex:35: ElixirLS.LanguageServer.Providers.DocumentSymbols.symbols/2
        (language_server) lib/language_server/server.ex:425: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 
```

I prefer not to disable `elixirLS.dialyzerEnabled`, so I hope I can get some suggestions, thanks!

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
