### ISSUE TITLE
Add UI support for enabling language server client tracing

### ISSUE THREAD

**Issue by justincjohnson** [JakeBecker/vscode-elixir-ls#137]
Per https://code.visualstudio.com/api/language-extensions/language-server-extension-guide, you can turn on language server client logging by setting `[langId].trace.server`.  As currently implemented, `[langId]` must be `ElixirLS` since this is the string used at https://github.com/JakeBecker/vscode-elixir-ls/blob/3f5bde06c23251a7a1eb5ef90ff3a60786efccc9/src/extension.ts#L58.  Note that case matters here.  I tried `elixirLS.trace.server` instead since that is the case used for the other options but it fails to produce the desired effect.

For this ticket we should add UI settings consistent with the other language servers for enabling tracing.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
