### ISSUE TITLE
Change langId from ElixirLS to elixir

### ISSUE THREAD

**Issue by justincjohnson** [JakeBecker/vscode-elixir-ls#139]
As mentioned in #137 it appears that we should be using `elixir` as the `langId` instead of `ElixirLS`.  This is consistent with the tracing docs at https://code.visualstudio.com/api/language-extensions/language-server-extension-guide and  https://github.com/Microsoft/language-server-protocol-inspector.

Maybe it doesn't matter a lot but #137 already introduces inconsistency in the configuration keys, using `ElixirLS` instead of `elixirLS`.

If changing to `elixir` is deemed too broad, perhaps we should just change all configuration properties from `elixirLS` to `ElixirLS` so we don't have to have this one special case.

**Comment by balduncle** [comment]
This rename would have an impact on existing config.  If we decide the change is worth it, we should research the appropriate way to migrate to new namespace for config.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
