### ISSUE TITLE
Syntax highlighting for interpolated strings

### ISSUE THREAD

**Issue by AntJanus** [JakeBecker/vscode-elixir-ls#140]
I tried to figure out if this is the right repo or not so redirect me to the ElixirLS repo if anything.

Most other language syntax highlighters use some kind of a setting to enable syntax highlight within an interpolated string. For example (in JavaScript using the Universe theme):

![image](https://user-images.githubusercontent.com/733810/60769040-94906c00-a088-11e9-8b7a-8acb131690ff.png)

While in Elixir:

![image](https://user-images.githubusercontent.com/733810/60769051-ab36c300-a088-11e9-839e-3c8ba8460a48.png)

I checked in other popular themes (Dark, Dark+, Solarized Dark, Night Owl, Gruvbox) and none of them highlight it but they have no issue highlighting JS interpolated strings. They can only highlight the brackets.

I'd appreciate help getting that feature in, or if it's already existing, the right JSON setting to change that color (and I'll go ahead and open issues/PRs for the themes to add support)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
