### ISSUE TITLE
Add a command to run Dialyzer

### ISSUE THREAD

**Issue by ccapndave** [JakeBecker/vscode-elixir-ls#141]
Although I love Dialyzer, I have to leave it turned off most of the time as it munches my CPU and makes my fans constantly spin up.

Therefore it would be lovely if there was a one-time `Run Dialyzer` command in VSCode that I could use on demand, instead of every time I save.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
