### ISSUE TITLE
Unused import

### ISSUE THREAD

**Issue by Paradox-3arthling** [JakeBecker/vscode-elixir-ls#142]
![logger missing](https://user-images.githubusercontent.com/11226110/61795536-5044f000-ae2c-11e9-971b-f4c74f5e94d5.PNG)
so I used `require Logger` and did use it...yet it still says "unused import".
Not sure if am using it wrong or it's a slight bug(Doesn't really effect anything*I hope*) but my OCD is just kicking in.

**Comment by delameko** [comment]
I can't seem to replicate this.  

Can you check on the output tab > ElixirLS dropdown and see if there's an error that stopping the language server from updating?

**Comment by Paradox-3arthling** [comment]
I'll just remove this issue in a few...I realized some error's pop when I don't even have one but after restarting the VS Code it ok.
