### ISSUE TITLE
Per project ElixirLS VSCode configuration

### ISSUE THREAD

**Issue by hewsut** [JakeBecker/vscode-elixir-ls#143]
I have a (painfully obvious?) question, but I've searched both repos and failed....so...here it goes.

I have two entirely separate Elixir repos. In repo one the Elixir project dir is in a subtree:

`/repo1/api/elixir`

In repo two it is at the root:

`/repo2/`

I find myself setting the VS code ElixirLS project directory (via `Preferences->Settings->Extensions->ElixirLS`) to `/repo1/api/elixir` when in repo one which then of course means ElixirLS is busted when I `cd` over to repo two, until I manually adjust the setting again back to root.

By chance...  is there anything like a `.elixir_ls_vscode` file-based config that I can write into each project that the VS code plugin can automagically pick up on?

**Comment by delameko** [comment]
When you open Preferences > Settings, there are some tabs across the top where you can choose settings for either User, Workspace or Folder.

**Comment by hewsut** [comment]
> You can, of course, change them in your user settings, or on a per project basis in .vscode/settings.json.

@delameko Gah..wow. 🤦‍♂  Thanks! Progress. So, now I have workspaces configured separately.

Is there anything special I need to do to ensure ElixirLS kicks off dialyzer for each workspace? Or a way to get more verbose feedback from ElixirLS?

No obvious errors being popped but I feel like they still are "stepping on each other" in some way as repo2 seems good to go but repo1 has not been analyzed.

**Comment by hewsut** [comment]
I think I've finally got it. For whatever reason, in repo1, ElixirLS was unhappy with the deps state and an explicit clean and compile got it on track.

Closing as mostly PEBKAC. 😄

**Comment by delameko** [comment]
If you go to View menu > Output, then on the little dropdown on the right, select ElixirLS.  That then displays the output from ElixirLS, very useful when things are acting odd 🙂
