### ISSUE TITLE
Fetching deps on save

### ISSUE THREAD

**Issue by yordis** [JakeBecker/vscode-elixir-ls#148]
Every time I save I see a message popup

![Screen Shot 2019-09-04 at 4 08 21 AM](https://user-images.githubusercontent.com/4237280/64249913-a98f4d00-cec9-11e9-82b8-920fff8e2cbe.png)

I am not sure what is going on

**Comment by gushonorato** [comment]
Mee too. It's quite annoying.

**Comment by tacoman667** [comment]
![image](https://user-images.githubusercontent.com/414641/69439789-431e0c00-0d0d-11ea-9c7c-4ffd70da058f.png)

Same here. Been happening for at least a few weeks for me. Oddly, if I switch `amqp` to `1.1` in mix file, it doesn't happen anymore. 

I use the terminal in the bottom frame all the time and this notification constantly blocks a lot of messages.

**Comment by logicmason** [comment]
This consistently blocks my view of the integrated terminal in the bottom 1/4 of the screen. My workflow is save, pop down to the terminal, type `iex -S mix phx.server` and then have my view obstructed by the fetching deps popup.

Is there any way of disabling it?

**Comment by DragosMocrii** [comment]
For those affected by this issue, see https://github.com/JakeBecker/elixir-ls/issues/71

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
