### ISSUE TITLE
README error

### ISSUE THREAD

**Issue by davelively14** [JakeBecker/vscode-elixir-ls#150]
This readme says it supports Elixir 1.6+, but it actually requires Elixir 1.7+:

![image](https://user-images.githubusercontent.com/12286657/65964471-1810ed80-e42b-11e9-99b1-d680a743944c.png)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
