### ISSUE TITLE
Cursor misplaced after code completion.

### ISSUE THREAD

**Issue by u2386** [JakeBecker/vscode-elixir-ls#152]
If no new line at the end of file, some code completion would misplace cursor position. e.g. do-end code block.

#### Expected
```elixir
1 defmodule KV.Registry |
2
```
Notice blank line 2. Normally, type do and hit enter, code completion would place cursor at head of the line between do and end keyword.
```elixir
1 defmodule KV.Registry do
2   |
3 end
4
```

#### Actual Instead
While, below, given no new line.
```elixir
1 defmodule KV.Registry |
```
Code completion would place cursor just after end keyword.
```elixir
1 defmodule KV.Registry do
2
3 end|
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
