### ISSUE TITLE
Cannot make ElixirLS work under VSCode on WLS and VSCode WSL extension

### ISSUE THREAD

**Issue by ferdef** [JakeBecker/vscode-elixir-ls#155]
Since I´ve discovered VSCode WSL extension I´ve been using as much as I can for every project and language (with Ruby it works perfectly). The problem is with Elixir, where I´m getting the familiar 

```The ElixirLS server crashed 5 times in the last 3 minutes```

This is what I´m getting on ElixirLS console output:

```[Trace - 5:48:13 PM] Sending request 'initialize - (0)'.
** (UndefinedFunctionError) function ElixirLS.Utils.WireProtocol.intercept_output/2 is undefined (module ElixirLS.Utils.WireProtocol is not available)
    ElixirLS.Utils.WireProtocol.intercept_output(&ElixirLS.LanguageServer.JsonRpc.print/1, &ElixirLS.LanguageServer.JsonRpc.print_err/1)
    lib/language_server/cli.ex:6: ElixirLS.LanguageServer.CLI.main/0
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:240: Code.eval_string/3```

Any clue?

**Comment by ferdef** [comment]
BTW, this is what `elixir -v` throws:

```Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 20)```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
