### ISSUE TITLE
Overwriting lint settings not working

### ISSUE THREAD

**Issue by taimur38** [JakeBecker/vscode-elixir-ls#157]
I have stuck "insertSpaces": false and "tabsizes": 4 in workspace settings, both in general and as an elixir language specific setting. But elixirls still overwrites and changes everything to 2 space tabs on save.

How do you actually overwrite these settings?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
