### ISSUE TITLE
How to restart ElixirLS in VSCode? (after changing the project directory for example)

### ISSUE THREAD

**Issue by sanjibukai** [JakeBecker/vscode-elixir-ls#159]
Hello,

I'm using ElixirLS with VSCode, in a dockerized environment..
Each time I touch to the project directory, I got a message inviting me to restart ElixirLS.
I know it's might be a stupid question, but how to do it?
Currently I simply close and reopen VSCode (but this is cumbersome and took some time because of the remote docker environment)
In this repository there is no mention at all of the word "restart" and in the other repository I found [these matches](https://github.com/JakeBecker/elixir-ls/search?q=restart&unscoped_q=restart) but this not really help me to know how to restart ElixirLS.

_NB: As a bonus question, does anyone know how to restart (or reload) VSCode from VSCode?
When disabling/enabling extensions there is a suggestion to reload VSCode, but I would know if it's possible to reload VSCode in other way_

_Edit: I found that by running the **Reload Window** from the Command menu, it restarts VSCode. And this seems to be sufficient to restart ElixirLS as well_
_So feel free to close. Cheers.._

Thank you

**Comment by alanvardy** [comment]
Hello!

I am not a maintainer of this project but would like to let you know that this repository has been inactive since May 2019. There is a fork that is being actively developed by community members, and I recommend you switch over!

The GitHub repository is here:
https://github.com/elixir-lsp/vscode-elixir-ls

And the Visual Studio Code extension is here:
https://marketplace.visualstudio.com/items?itemName=elixir-lsp.elixir-ls

If you are having any issues or would like to open any pull requests, please try the new extension or clone the new repository first. You may find that the problem is already resolved 🙂

Thank you and happy Elixiring.

**Comment by sanjibukai** [comment]
Hello! Thanks for taking the time to answer..
In fact there were no problems at all, I just asked how I can restart the LSP server, but indeed reloading VSCode is enough.

And FYI I'm still using your version since I don't know why but the fork didn't work in VSCode docker remotes (using .devcontainer) which make it pretty useless :/

So thanks again for all the efforts you put into it..

**Comment by alanvardy** [comment]
I'm unfortunately not a contributor to the fork either, just trying to raise awareness of its existence to all who end up at this repo.

Best of luck, and please consider opening a pull request over there!
https://github.com/elixir-lsp/vscode-elixir-ls

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
