### ISSUE TITLE
Issue with format on save

### ISSUE THREAD

**Issue by blcksheep80** [JakeBecker/vscode-elixir-ls#166]
I upgraded VSCode to:

Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T11:22:13.689Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-46-generic snap

Seems that format on save now hangs.

**Comment by blcksheep80** [comment]
NVM. Never noticed a bug in my module naming and it seems there was a collision. Closing this. Apologies

**Comment by axelson** [comment]
@blcksheep80 out of curiosity could you give details of what the naming collision was?
