### ISSUE TITLE
"editor.acceptSuggestionOnEnter": "on" is set, but does not work

### ISSUE THREAD

**Issue by vivdiwakar** [JakeBecker/vscode-elixir-ls#167]
Hi team,

First off - great product - thank you!

Secondly, as the subject say, I have set "editor.acceptSuggestionOnEnter" to "on", but this does not seem to have an effect and hitting Enter creates a newline.

I have this set in both the master settings.json for Code, as well as within the project I am working.

Thanks.

**Comment by delameko** [comment]
Hi @vivdiwakar, development of this extension has moved to [elixir-lsp/vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls).

**Comment by vivdiwakar** [comment]
Understood @delameko, apologies for posting in the wrong place. Will re-post.

**Comment by vivdiwakar** [comment]
Realise I had the older plugin installed, updated to elixir-lsp version - all working now.
