### ISSUE TITLE
Output window focus grabbing is annoying

### ISSUE THREAD

**Issue by bcardarella** [JakeBecker/vscode-elixir-ls#19]
If compilation fails for any reason (switching between branches for example) the focus is changed from the active tab (i.e. terminal) and the output tab is given focus.

According to: https://github.com/Microsoft/vscode/issues/31474#issuecomment-319032829 this is the responsibility of the addon.

**Comment by JakeBecker** [comment]
Appreciate the documentation link! I just published v0.2.6 which fixes this.
