### ISSUE TITLE
.formatter.exs support?

### ISSUE THREAD

**Issue by potz** [JakeBecker/vscode-elixir-ls#21]
First of all thanks for publishing this, it's awesome!

I wonder if it would be too difficult to add support to formatter customizations via `.formatter.exs` file (as per [this article](http://devonestes.herokuapp.com/everything-you-need-to-know-about-elixirs-new-formatter))?

I can make it work by calling `mix format`, but not with the `formatOnSave` setting of vscode...

**Comment by JakeBecker** [comment]
Thanks for filing the issue -- I had been meaning to get around to doing this. I just published v0.2.7 which reads formatter options from `.formatter.exs` in the project root. Give it a try!

**Comment by potz** [comment]
Works flawlessly! Wow that was quick, thanks a lot!

**Comment by RaymondLoranger** [comment]
In **.formatter.exs** however, **locals_without_parens** is not taken into consideration it seems.

**Comment by rafaelbiten** [comment]
Yep, apparently I'm having the same issue as you @RaymondLoranger 
Did you find a way to make it work for you?
Tks!
