### ISSUE TITLE
Is there a way to specify source path?

### ISSUE THREAD

**Issue by luckynum7** [JakeBecker/vscode-elixir-ls#23]
Hi @JakeBecker, I've read your blog and found the plugin helpful.

However, I used a monorepo when the mix.exs was in path like `/project-root/elixir/mix.exs`.

Is there a way to specify source path?

Btw, vscode-elixir provided `elixir.projectPath` for it. https://github.com/fr1zle/vscode-elixir/issues/82

**Comment by micahrye** [comment]
@luckynum7 ElixirLS configuration also provides

from vscode default settings
```
// Subdirectory containing Mix project if not in the project root
"elixirLS.projectDir": "",
```

I also work in a monrepo and while I have tried absolute and relative paths for `elixirLS.projectDir` I continue to get the following if I try and run the debugger.

```
[error] Process #PID<0.101.0> raised an exception
** (Code.LoadError) could not load /Users/micahrye/code/work/bulb/repos/bulb/mix.exs
    (elixir) lib/code.ex:1023: Code.find_file/2
    (elixir) lib/code.ex:628: Code.load_file/2
    (debugger) lib/debugger/server.ex:437: ElixirLS.Debugger.Server.initialize/1
```

You can see that something is trying to access ` /Users/micahrye/code/work/bulb/repos/bulb/mix.exs` which does not exist. 

In this, the relevant mix file is at `/Users/micahrye/code/work/bulb/repos/bulb/environments/gateway/src/sysfs/mix.exs`

**Comment by JakeBecker** [comment]
Apologies for neglecting this old issue.

Recent releases support the configuration setting `elixirLS.projectDir` which allows you to specify a subdirectory as your project root. The setting is also supported in your launch configurations for debugging, but there you have to set it as `"${workspaceRoot}/path/to/subdir"`. (I might be able to improve this to make them consistent.)
