### ISSUE TITLE
Confusing error in mix.exs

### ISSUE THREAD

**Issue by mattbaker** [JakeBecker/vscode-elixir-ls#29]
When I have Poison as a dependency I'm getting this error and I haven't been able to figure it out on my own. I'm hoping someone may be able to point me in the right direction.

In vscode-elixir-ls this error pops up. I'm unable to reproduce with with a `mix compile` or a `mix xref deprecated`. I'm unable to copy the trace in the UI, but if there's a way to get the whole trace so I can dump it here (presumably useful) let me know.  Instead I just have this screenshot, my apologies there.

<img width="1234" alt="screen shot 2018-01-07 at 11 11 48 am" src="https://user-images.githubusercontent.com/55462/34653090-d07b6710-f39b-11e7-8ccb-cdab28cbc388.png">

I can't for the life of me figure out why `Poison.__info__(:deprecated)` is throwing a no clause error.

Any insights?

**Comment by akappen** [comment]
I am seeing the exact same issue. For me it only appeared when I edited a dependency in the mix file.

I was able to fix it by clearing the elixir_lx cache in the workspace root:
`rm -r .elixir_ls/*`

**Comment by mattbaker** [comment]
I'll give that a try. Does the issue resurface later or does it "stay fixed"?

Also interesting, it seems to be spurious as I'm poking around. This is odd!

**Comment by ratbag98** [comment]
Switching to the Output tab of the, you can see the full text (deleting .elixir_ls didn't fix it for me):

```
Compiling with Mix env test

[Error - 10:55:46] Process #PID<0.122.0> raised an exception
** (FunctionClauseError) no function clause matching in Poison.__info__/1
    Poison.__info__(:deprecated)
    (mix) lib/mix/tasks/xref.ex:335: Mix.Tasks.Xref.load_exports_and_deprecated/1
    (mix) lib/mix/tasks/xref.ex:326: Mix.Tasks.Xref.load_exports_and_deprecated_into_acc/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/xref.ex:295: anonymous fn/2 in Mix.Tasks.Xref.source_warnings/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/tasks/xref.ex:291: Mix.Tasks.Xref.source_warnings/2
    (mix) lib/mix/tasks/xref.ex:182: Mix.Tasks.Xref.warnings/1
```

**Comment by mattbaker** [comment]
I've yet to see this pop up for some time now. I'm going to close. I'll re-open if it appears again.

**Comment by JakeBecker** [comment]
The language server depends on Poison, and since your project gets compiled in the same VM as the language server, it's possible that the Poison dependency in your project and the one in the language server are interfering with each other somehow. Unfortunately, it's probably not an easy fix, so as long as it's not a frequent problem I'm probably gonna ignore it.

**Comment by mattbaker** [comment]
Sounds good, thanks for the insight!
