### ISSUE TITLE
.elixir_ls folder in project

### ISSUE THREAD

**Issue by jhaddow** [JakeBecker/vscode-elixir-ls#30]
Is the `.elixir_ls` folder needed in the project? Can it be saved somewhere else? I don't want those files tracked by git, and it'd be nice if I can avoid having to put the folder in `.gitignore`

**Comment by GoNZooo** [comment]
I would suggest adding it to your git exclude file (found at `.git/info/exclude`). It works exactly like `.gitignore` except it's not itself tracked in your git repo, so you can use it for whichever things you don't want to track but are really only specific to you.

If you don't want to mess with it manually, there are extensions for adding things to exclude from the file context menu, such as: `jcmordan.mark-as-excluded`. I use `boukichi.git-exclude` which has a command that lets you open the exclude file.

**Comment by tmepple** [comment]
The folder is needed by the incremental Dialyzer.  

I kept forgetting to add it to `.gitignore` and I've been bitten by `node_modules` not being in some standard `.gitignore` files so I just added it to my global git config, which works great.

So in my global `~/.gitconfig` I have:
```
[core]
    excludesfile = /Users/tepple/.gitignore.global
```
My `.gitignore.global` file is formatted like a normal `.gitignore` file, so I have entries like so:
```
.DS_Store
node_modules/
.elixir_ls/
```

**Comment by jhaddow** [comment]
These are both great suggestions. Thanks!

**Comment by JakeBecker** [comment]
My recommendation is to add `.elixir_ls` to your global gitignore file. It's pretty common for IDEs to save config data to your project directory -- VS Code has `.vscode`, IDEA has `.idea`, etc, and this is the usual solution.
