### ISSUE TITLE
Improve syntax highlighting

### ISSUE THREAD

**Issue by pablobcb** [JakeBecker/vscode-elixir-ls#32]
I'm not sure if this repo is responsible for such task but, it would be really nice to have colours on atoms, pipe operators, and keyword-lists keys ..

if pointed to the right direction I could try to submit a PR

Thank you for awesome IDE integration!

**Comment by TeeSeal** [comment]
I seem to have syntax highlighting for everything you mentioned:
![image](https://user-images.githubusercontent.com/14080148/35486159-c14dfb08-0472-11e8-8307-d4b534921952.png)

And if you mean `atoms` as in module names (which are currently not highlighted except on declaration), I have a PR open for that: https://github.com/JakeBecker/vscode-elixir-ls/pull/35

**Comment by pablobcb** [comment]
almost everything is white here, what theme are you using?

**Comment by JakeBecker** [comment]
Just published v0.2.11 with @TeeSeal's improvements.

**Comment by DragosMocrii** [comment]
@TeeSeal what font are you using that achieves those font ligatures? Also, I've tried Ayu Mirage Mod but it doesn't look like your screenshot..

**Comment by TeeSeal** [comment]
@DragosMocrii was too long ago for me to remember exactly, but it should be Fira Code.

Also, Ayu Mirage has changed quite a while ago. Their colors are a bit different now. If you're looking to get the same colors look for Ayu Legacy.

**Comment by DragosMocrii** [comment]
@TeeSeal Thanks you! Fira Code looks awesome!
