### ISSUE TITLE
Phoenix Config for debugger

### ISSUE THREAD

**Issue by micahrye** [JakeBecker/vscode-elixir-ls#33]
I have been using vscode-elixir-ls on some library projects and now want to use in a Phoenix app. The issue is that the debugger does not start the phoenix server (phx.server) unless using the vscode-elixir-ls "test" configuration. Glad it works there, but when doing dev, I would like to use the debugger without going through all my test. 

Do I need to add arguments to the vscode config file? It would be nice to have some documentation on what/how to configure vscode-elixir-ls

Here is my config for vscode-elixir-ls: 
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "type": "mix_task",
      "name": "mix dev",
      "request": "launch",
      "projectDir": "${workspaceRoot}"
    },
    {
      "type": "mix_task",
      "name": "mix test",
      "request": "launch",
      "task": "test",
      "taskArgs": [
        "--trace"
      ],
      "startApps": true,
      "projectDir": "${workspaceRoot}",
      "requireFiles": [
        "test/**/test_helper.exs",
        "test/**/*_test.exs"
      ]
    }
  ]
}
```

**Comment by atelles** [comment]
I couldn't figure out how to debug a Phoenix project, an example would be very much appreciated.

**Comment by JakeBecker** [comment]
Sorry for the wait in responding to this. You need to create a configuration with `"task": "phoenix.server". The default task for Phoenix projects (which is run when you do `iex -S mix`, for example) doesn't start a server.

I may add some help text to the "task" option to suggest doing this for Phoenix projects.

**Comment by atelles** [comment]
Thanks @JakeBecker! I'm not sure what I was doing wrong, but adding this configuration (launch.json) solved my problem:

```
{
    "type": "mix_task",
    "name": "start phoenix",
    "request": "launch",
    "projectDir": "${workspaceRoot}",
    "task": "phx.server"
}
```

**Comment by Razzeee** [comment]
"phx.server" as a task hast to match a task in `task.json` right?

Is there a `task.json` for phoenix around that I'm not able to find? This is what I'm trying to use.
It does do something, but if I launch it via `launch.json` it starts the debugger, compiles sometimes but the website doesn't seem to be reachable? It even seems like the debug process (as in the play/stop etc controls) crashes as soon as I try to go to the website in my browser.
````
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "run",
            "type": "shell",
            "command": "mix",
            "args": [
                "phx.server"
            ],
            "problemMatcher": [
                "$mixCompileError",
                "$mixCompileWarning"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
        {
            "label": "test",
            "type": "shell",
            "command": "mix",
            "args": [
                "test"
            ],
            "problemMatcher": [
                "$mixCompileError",
                "$mixCompileWarning",
                "$mixTestFailure"
            ],
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
```

**Comment by JakeBecker** [comment]
@Razzeee A basic Phoenix server task in `launch.json` looks like this:
```
{
      "type": "mix_task",
      "name": "mix phx.server",
      "request": "launch",
      "projectDir": "${workspaceRoot}",
      "task": "phx.server"
    }
```

The `"task"` field in the json specifies the Mix task.

**Comment by JakeBecker** [comment]
`task.json` is a general-purpose way to run CLI commands from within VS Code, it's mostly language-independent and isn't directly tied into the debugger or the language server. Based on your "problem matchers", it looks like you were using the other VS Code Elixir plugin which uses these tasks for compilation, but that isn't necessary with ElixirLS, so you can remove it if you want.

**Comment by Razzeee** [comment]
That's good to know, I just started looking into this today and indeed switched from vscode-elixir. But also just created the task.json as I found the matchers in ElixirLS https://github.com/JakeBecker/vscode-elixir-ls/blob/master/package.json#L266 so that got me confused I guess.

**Comment by Razzeee** [comment]
And is there a reason to not add `"task": "phx.server"` here? https://github.com/JakeBecker/vscode-elixir-ls/blob/master/package.json#L230
As that launch config should be pretty agnostic anyway?

**Comment by tlatforlz** [comment]
my configuration (launch.json) : 
```
        {
            "type": "mix_task",
            "name": "start phoenix",
            "request": "launch",
            "projectDir": "${workspaceRoot}",
            "task": "phx.server"
        }
```
But I got a error
```
(Debugger) Initialization failed because an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :on_load_failure}
        int.erl:531: anonymous fn/3 in :int.load/2
        int.erl:527: :int.load/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (debugger) lib/debugger/server.ex:469: ElixirLS.Debugger.Server.initialize/1
```
Is there have other config in launch.json or config in project?

**Comment by Razzeee** [comment]
```````
