### ISSUE TITLE
Unable to open 'undefined': no provider for undefined

### ISSUE THREAD

**Issue by alex88** [JakeBecker/vscode-elixir-ls#37]
While debugging and having the debugger stopped on a line, every time I try to step into the next one I get the error on the top `Unable to open 'undefined': no provider for undefined`.
Anyone else had the same problem?

**Comment by JakeBecker** [comment]
Can you reproduce this with the latest release? If so, please post a screenshot of the error.

**Comment by fanfan70** [comment]
I have the same problem, it appeared (quite randomly) since I started using the "Debugger for Chrome" plugin.
Here's a snapshot :
![pb-vscode](https://user-images.githubusercontent.com/34914169/39245558-6e112aee-4894-11e8-9cb7-3a1349c78aa5.png)

**Comment by JakeBecker** [comment]
It looks like you're debugging typescript not Elixir. Are you sure that has to do with the ElixirLS extension?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
