### ISSUE TITLE
Opening a project on Windows 10 just keeps trying to build core Elixir PLT

### ISSUE THREAD

**Issue by kofno** [JakeBecker/vscode-elixir-ls#38]
Plug-in works great on my Mac, but on Windows it just keeps flashing `Building core Elixir PLT. This will take a few minutes.` and the CPU is pegged. None of the features are working except syntax highlighting. Not sure how to help debug what may be happening. I don't see any errors in the developers tools.

Can you offer any pointers that will help me figure out what may be wrong?

**Comment by EslaMx7** [comment]
Same issue here, I see there is an exception in the problems tab with this message: 
```
file: 'file:///d%3A/Projects/project_name/mix.exs'
severity: 'Error'
message: 'an exception was raised:
    ** (Mix.Error) Could not compile with "nmake" (exit status: 2).
One option is to install a recent version of
[Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)
either manually or using [Chocolatey](https://chocolatey.org/) -
`choco install VisualCppBuildTools`.

After installing Visual C++ Build Tools, look in the "Program Files (x86)"
directory and search for "Microsoft Visual Studio". Note down the full path
of the folder with the highest version number. Open the "run" command and
type in the following command (make sure that the path and version number
are correct):

    cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

This should open up a command prompt with the necessary environment variables
set, and from which you will be able to run the "mix compile", "mix deps.compile",
and "mix test" commands.

        (mix) lib/mix.ex:291: Mix.raise/1
        lib/mix/tasks/compile.make.ex:95: Mix.Tasks.Compile.ElixirMake.run/1
        (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
        (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
        (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
        (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
        (mix) lib/mix/tasks/compile.all.ex:34: Mix.Tasks.Compile.All.with_logger_app/1
        (mix) lib/mix/task.ex:314: Mix.Task.run_task/3'
at: '1,1'
source: 'ElixirLS'
code: 'undefined'
```

My assumption is the extension runs `mix compile` and `mix deps.compile` on activation, which on _Windows_ requies to add some environment variables that can be added by this command in the shell : `cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64`

**My workaround for this issue is :**
- Open a command prompt at the project path
- Run `cmd /K "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64`
- Open _VSCode_ from the same shell using `code .` command

**Now** everything should be OK, and the extension should able to compile the project successfully.

> Works on my machine: Windows 10 (Visual Studio 2017 installed)

**Comment by allansson** [comment]
@kofno: To get an error log, open the command palette (`Ctrl + Shift + P`), search for _Toggle Output_ and select _ElixirLS_ in the dropdown to the right.

I had a similar problem, but my output log differs from @EslaMx7.

```
Pid: #PID<0.244.0>
Start Call: ElixirLS.LanguageServer.Dialyzer.start_link({#PID<0.101.0>, "<redacted>"})
[Error - 10:26:24] Process #PID<0.248.0> raised an exception
** (ErlangError) Erlang error: {:nocatch, {:dialyzer_error, '    The PLT file c:/Users/<redacted>/.mix/elixir-ls-20.2_elixir-1.6.1 is not writable'}}
    dialyzer_cl.erl:685: :dialyzer_cl.cl_error/1
    dialyzer_cl.erl:376: :dialyzer_cl.do_analysis/4
    dialyzer.erl:160: :dialyzer.run/1
    (language_server) lib/language_server/dialyzer/manifest.ex:122: ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0
    (language_server) lib/language_server/dialyzer/manifest.ex:16: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0
[Error - 10:26:24] Child ElixirLS.LanguageServer.Dialyzer of Supervisor #PID<0.103.0> (ElixirLS.LanguageServer.Dialyzer.Supervisor) terminated
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: {:nocatch, {:dialyzer_error, '    The PLT file c:/Users/<redacted>/.mix/elixir-ls-20.2_elixir-1.6.1 is not writable'}}
        dialyzer_cl.erl:685: :dialyzer_cl.cl_error/1
        dialyzer_cl.erl:376: :dialyzer_cl.do_analysis/4
        dialyzer.erl:160: :dialyzer.run/1
        (language_server) lib/language_server/dialyzer/manifest.ex:122: ElixirLS.LanguageServer.Dialyzer.Manifest.build_elixir_plt/0
        (language_server) lib/language_server/dialyzer/manifest.ex:16: anonymous fn/1 in ElixirLS.LanguageServer.Dialyzer.Manifest.build_new_manifest/0
Pid: #PID<0.247.0>

... continues to retry ad-infinitum
```

It turned out that I hadn't run any `mix` commands yet and therefore the path `%USERPROFILE\.mix` did not exist. After I did `mix deps.get` and installed `hex`, it started working again.

**Comment by kofno** [comment]
@allansson your solution worked for me, too. Thanks!

**Comment by JakeBecker** [comment]
@allansson Thank you for finding the fix!

I've released v0.2.12 which ensures this directory is created to prevent this problem: https://github.com/JakeBecker/elixir-ls/commit/546c535e117bae7046ed4902e2da5562322d6e9d

**Comment by mercurio** [comment]
This doesn't appear to be fixed in Atom yet. I had to disable ide-elixir to get rid of the notice. I'm on Ubuntu 16.04, Atom 1.26.1 and ide-elixir 0.2.19, and I verified that my ~/.mix directory exists and is writable.

**Comment by glauciom** [comment]
@mercurio same thing here as well for Atom.

**Comment by egeersoz** [comment]
@EslaMx7's workaround worked for me. Specifically, the third bullet point is what I was missing: you have to run VS Code from the same shell on which you run `vcvarsall.bat`.
