### ISSUE TITLE
How to silence warnings for a module?

### ISSUE THREAD

**Issue by bottledsmoke** [JakeBecker/vscode-elixir-ls#39]
EDIT

I figured it out. I'll leave this up so that people can google it in the future, but you're going to use a module attribute to silence the function. 

    #module: diaylzer, supress warnings for function __ex_unit_setup_0/1
    @dialyzer {:nowarn_function, __ex_unit_setup_0: 1}

Works just fine. Error list is now clean. I can feel my anxiety going down by the second. 

---

ORIGINAL POST

Both Phoenix 1.2.5 and 1.3.0 come with a function in their test suites that have no local return value. It's not a big deal that it's there, but the error is constantly highlighted in my Tree. I'm a little obsessive about having 0 errors and highlights in my tree at the end of the day, and that one green file is getting my goose. I've found documentation for how to silence Dialyzer in Erlang projects on a per-module basis, but I can't find or figure out a way to silence the error when using the VS-Code plugin. 

Including something like this...

    -dialyzer({nowarn_function, f/0}). # translated to Elixir, mind you

Isn't working as I have no reference to elixirLS, dialyzer on the erlang module, or dialyxir.

The error code is...

    file: '...persona_stuff.../test/support  /conn_case.ex'
    severity: 'Warning'
    message: 'Function '__ex_unit_setup_0'/1 has no local return'
    at: '30,3'
    source: 'ElixirLS Dialyzer'
    code: 'undefined'

Help an OCD fella out! :)

**Comment by AlchemistCamp** [comment]
On a related note, it's a bit rough having red squigglies on every single line in a mix file just because of comeonin/bcrypt compilation. It kind of gets in the way of the work.

**Comment by JakeBecker** [comment]
Thanks for adding the solution, @bottledsmoke .  The docs for the `@dialyzer` attribute are not super obvious and I should probably link them from the documentation somewhere.
