### ISSUE TITLE
Multi-folder workspace causes 'No mixfile found in project root'

### ISSUE THREAD

**Issue by jeroenvisser101** [JakeBecker/vscode-elixir-ls#41]
I'm trying to disable the extension for one of the folders (a Vue.js project) in my workspace to get rid of the 'No mixfile found in project root' error, but I can't seem to find a way documented. Is there any way of disabling elixir-ls for one folder of a multi-folder workspace in vscode?

**Comment by JakeBecker** [comment]
Looks like the APIs for multi-folder workspaces are still a little unstable, but docs for how to handle it exist: https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#language-client--language-server

**Comment by jeroenvisser101** [comment]
> For what it's worth, you can disable an extension on a per-workspace basis from the Extensions pane in VS Code.

I have the following folder structure:
- `admin` (a Vue.js project)
- `api` (a Elixir project)



> As far as I can tell, VS Code launches the language server in the first folder in the workspace, and the others are ignored.

This is what I also found, which is super weird, and also not configurable as a user (afaik). [This](https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-multi-server-sample) is supposed to be the example that would fit best with elixir-ls, I guess?

**Comment by jclem** [comment]
I’ve at least worked around the issue of Elixir support being disabled by ensuring my Elixir project is listed first in my workspace settings. I still get a warning about the non-Elixir project, but everything works fine in the Elixir one, at least.

**Comment by thezjy** [comment]
I guess `elixirLS.projectDir` is not the answer? It's weird because the TypeScript plugin works fine in this situation. I'd like to take a look at this issue because it's really annoying.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
