### ISSUE TITLE
Code formatting does not work

### ISSUE THREAD

**Issue by polaris6933** [JakeBecker/vscode-elixir-ls#42]
I installed the extension from inside of VS Code and, as the tile says, neither auto formatting (I enabled it in User Settings) nor manual (with Alt + Shift + F) works. Erlang is version 20 and Elixir - 1.6.1 and I'm on Linux.

**Comment by JakeBecker** [comment]
Can you paste the contents of the "Output" pane in VS Code after hitting the format hotkey?

**Comment by polaris6933** [comment]
Nothing appears there. Don't know if that's related but I tried setting up simple tasks to run mix commands, like this:

```
{
    "label": "mix",
    "type": "shell",
    "command": "mix"
    "args": [
        "format"
    ]
}
```
and when I try to run them I get the following error: 

/bin/bash: mix: command not found
The terminal process terminated with exit code: 127

**Comment by polaris6933** [comment]
Okay, I think the problem is actually on my end. I noticed that the auto completion feature also does no work for me and the debugger doesn't start (I thought I had just not set it up properly) but after that I tried vscode-elixir and that also did not work for me (basically I'm only getting syntax highlighting from both extensions). In contrast, I tried the extensions on Windows and they both just work.

**Comment by JakeBecker** [comment]
`mix` needs to be available in your path for the extension to launch. Check that you can run `mix` commands from the terminal. If that works, there's likely some problem with VS Code picking up your path correctly when launched.

Gonna close this on the assumption that it's not a problem with the language server, though it sounds like it'd be good to have a clear error message when this happens.

**Comment by JakeBecker** [comment]
Try downloading the `elixir-ls.zip` [here](https://github.com/JakeBecker/elixir-ls/releases) and extract it, then try running `language_server.sh` (or `.bat` on Windows) from a terminal. If that fails, hopefully it'll give a more informative error. If it works, I probably should add better logging to the extension so we can figure out what's going on when it fails to launch.
