### ISSUE TITLE
Consider enabling `editor.quickSuggestions` by default again

### ISSUE THREAD

**Issue by maxmellen** [JakeBecker/vscode-elixir-ls#48]
Hi there 👋

### Issue

I have been having a great time using this extension, and I think it shows great promise for tooling in the Elixir community.

Excited about it as I am, I have been showing this extension to other Elixir programmers, and one of the first things they notice about this extension is the lack of autocomplete. I then proceed to explain to them that there is no such lack, but that the `quickSuggestions` behavior is turned off by default for Elixir under this extension, and that autocompletion with `Ctrl-Space` or after a `.` still works perfectly, and that this can be turned back on in the user settings.

I think this is a bit jarring for VS Code users as it isn't the default behavior shown with the built-in language support.

I read your concerns about `quickSuggestions` in the [changelog](https://github.com/JakeBecker/vscode-elixir-ls/blob/master/CHANGELOG.md#v028-29-nov-2017):

> Disable `editor.quickSuggestions` by default so autocomplete suggestions are triggered automatically only when after a ".". This is nice because the language server irritatingly tries to auto-complete things like "do" or "else" if they come at the end of a line.

However, after having updated the snippets, I feel like these concerns are largely addressed as you can see in the screencast below.

Considering this behavior is a bit jarring for VS Code users, and the issues you mentioned seem to be addressed, could we consider turning `editor.quickSuggestions` back on by default for the sake of approachability?

I hate to see other Elixir developers quickly discard this extension for the wrong reasons.

### Screencast ✨ 

![elixir_ls](https://user-images.githubusercontent.com/17215508/36975910-005d7344-207c-11e8-9651-3d0558dd322c.gif)

Best 🤗

**Comment by namkai** [comment]
👍 I agree with this!

**Comment by JakeBecker** [comment]
I appreciate the feedback. I'm working on some improvements to autocompletion that should solve the annoyances that led me to turn it off, and I'll re-enable it by default in the next release.

**Comment by maxmellen** [comment]
Alright! Looking forward to see what you have in store! 🙂

**Comment by JakeBecker** [comment]
I've just published v0.2.15 with quickSuggestions re-enabled. It's still... occasionally annoying. If the server thinks slower than you type, sometimes it misses the `do...end` snippet or replaces an `else` with something you really didn't want it to, but it's definitely better now than before. Give it a try!
