### ISSUE TITLE
would you accept a PR to add problemMatchers?

### ISSUE THREAD

**Issue by pragdave** [JakeBecker/vscode-elixir-ls#50]
I was planning to steal the regex from vscode-elixir and just add them to the package.json here.

Dave

**Comment by JakeBecker** [comment]
That shouldn't be necessary. If you're using Elixir 1.6, the language server should compile your project for you and report any build warnings or errors. If you're using Erlang/OTP 20, you should get Dialyzer warnings too. Is that not working for you?

**Comment by pragdave** [comment]
That's working great. But I'd like to catch errors running tests, too.


On Mon, Mar 05, 2018 at 12:30pm, Jake Becker < notifications@github.com [notifications@github.com] > wrote:
That shouldn't be necessary. If you're using Elixir 1.6, the language server should compile your project for you and report any build warnings or errors. If you're using Erlang/OTP 20, you should get Dialyzer warnings too. Is that not working for you?

**Comment by JakeBecker** [comment]
Merged! I would like to eventually have an option to run tests automatically from the language server, but the problem matchers are an okay stopgap for now.

**Comment by pragdave** [comment]
Many thanks!
