### ISSUE TITLE
Autocomplete # to #{} while inside a String

### ISSUE THREAD

**Issue by atelles** [JakeBecker/vscode-elixir-ls#51]
I think most of the time someone types a '#' inside a String it's to do an interpolation.

So it would be nice if when we type '#' inside a String, it would already autocomplete to '#{}' and move the cursor after the '{', just like when you open a parenthesis.

PS. Not sure, it this issue should be here or on ElixirLS.

**Comment by quolpr** [comment]
Yeah, good idea. Was missing this feature after atom

**Comment by teamon** [comment]
From my personal experience this is more annoying than useful, esp. when typing markdown headers inside `@doc` block multiline string:

```elixir
@doc """
### Header
"""
```

**Comment by crbelaus** [comment]
This issue could be somewhat mitigated in PR #122. When typing `#{` inside a string, the corresponding `}` will be automatically inserted at the end of the cursor.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
