### ISSUE TITLE
Subfolder with Elixir not recognised

### ISSUE THREAD

**Issue by Ilyes512** [JakeBecker/vscode-elixir-ls#57]
Hey,

Not sure if this belongs here (and so is specific to VSCode) or if it should be in elixir-ls...

When I have my code inside a subfolder, ElixirLS does not recognise it as a Elixir project. It probably is only search for a mix file in the root of the workspace. In this case it's not a umbrella app, but a project that uses docker-compose. What I like to do is move all "code" in inside a `src` folder:

```
.
├── docker-compose.yml
└── src
    ├── README.md
    ├── config
    │   └── config.exs
    ├── lib
    │   ├── example_app
    │   │   └── application.ex
    │   └── example_app.ex
    ├── mix.exs
    └── test
        ├── example_app_test.exs
        └── test_helper.exs
```

Is there a way I could make the above work. Somehow tell ElixirLS to look inside the src folder?

Thanks!

**Comment by JakeBecker** [comment]
Set `elixirLS.projectDir` to `"src"` in your `.vscode/settings.json`.

**Comment by Ilyes512** [comment]
Oh nice! Will try that :)
