### ISSUE TITLE
Intellisense immediate dropdown

### ISSUE THREAD

**Issue by thdxr** [JakeBecker/vscode-elixir-ls#60]
I've noticed I have to press `ctrl+space` to get the intellisense to show up unless I type a module name then a period.  I've compared this to the intellisense for other languages (Typescript) where the dropdown shows up as soon as I start typing.

Is there some kind of limitation preventing immediate intellisense?

**Comment by thdxr** [comment]
Realized this is a vscode setting

```
    "[elixir]": {
        "editor.quickSuggestions": true
    }
```

**Comment by JakeBecker** [comment]
Check that you're using the latest release. Having it off was the default a few releases ago but now it's on again by default.
