### ISSUE TITLE
ElixirLS published with wrong version number on VS Code Marketplace

### ISSUE THREAD

**Issue by maxmellen** [JakeBecker/vscode-elixir-ls#61]
Hi there 👋 

Just a heads up that the current ElixirLS extension for VS Code (v0.2.18) is released under the wrong version number on the VS Code Marketplace (v0.2.19).

<img width="594" alt="screen shot 2018-04-03 at 11 41 00" src="https://user-images.githubusercontent.com/17215508/38242047-0ed9bef4-3734-11e8-9837-f291044aa41d.png">

This doesn't actually cause any problems, just thought that it might be problematic when releasing the next version, especially if that hasn't been brought to your attention by then.

Best ✨

**Comment by JakeBecker** [comment]
I occasionally have to publish updates that only involve the client code, and so keeping the versions in sync has turned out to be a bad strategy. I will probably decouple the version numbers completely at some point. But thanks for pointing it out!

**Comment by maxmellen** [comment]
Yeah, I can't imagine the client and server versions would be able to stay in sync for too long, but in this instance, I was specifically talking about the client code.

Looking at this commit https://github.com/JakeBecker/vscode-elixir-ls/commit/fab283fdaeab7f08301bc066a487e812e454585f I'm actually super confused. In the package.json file, I imagine you're talking about the client version but what about the changelog? It would be least confusing if the changelog in this repo referred to the client code's versions and maybe said something like "Upgrade ElixirLS server to 0.2.y".

Did you just make a small mistake when writing the version numbers or did you do this on purpose and am I missing something?

At the end of the day, I just wanted to bring this to your attention.

Best ✨

**Comment by JakeBecker** [comment]
Oh, you're right. I accidentally bumped the version number by two. Thanks for figuring that out! I will correct it in the next release.
