### ISSUE TITLE
Warning about "Dependency specified in the wrong format" never goes away

### ISSUE THREAD

**Issue by ORBAT** [JakeBecker/vscode-elixir-ls#64]
I don't know whether this is an extension problem, or a problem with ElixirLS. Drop me a note if I should open an issue on the ElixirLS side.

## Versions used

* `elixir --version`: Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]Elixir 1.6.4 (compiled with OTP 20)
* OS: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64 (macOS 10.12.6 (16G1212))

## Steps to reproduce

1\. Create mix project, open it in vscode. Replace `mix.exs` with [this](https://gist.github.com/ORBAT/d3012b26f2d4850da239839cf06ff2c4). Save the file.

This should result in the entire file being underlined, with the following error
```
** (Mix.Error) Dependency specified in the wrong format:

    {}
```

2\. remove the `{}` on line 23, save the file.

## Expected outcome

Error disappears.

## Actual outcome

The error doesn't go away despite saving. 

The [ElixirLS log](https://gist.github.com/ORBAT/6b76c159cb6a16d79b0afc345b06aee6) looks like it's trying to compile a stale version of the file. If I reload the window, the error goes away and ElixirLS is happy.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
