### ISSUE TITLE
Cannot get formatter to work on an umbrella app

### ISSUE THREAD

**Issue by dideler** [JakeBecker/vscode-elixir-ls#65]
Saving the file doesn't run the formatter, and using <kbd>shift</kbd>+<kbd>alt</kbd>+<kbd>f</kbd> to run the formatter pops up an error message saying "There is no formatter for 'elixir'-files installed".

```
$ elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 19)
```

**Comment by dideler** [comment]
Reinstalling the extension didn't help.

**Comment by JakeBecker** [comment]
Please re-file this issue on [ElixirLS](https://github.com/JakeBecker/elixir-ls) and add the info from the [issue template](https://github.com/JakeBecker/elixir-ls/blob/master/ISSUE_TEMPLATE.md) there. Thanks!
