### ISSUE TITLE
Different color highlight for specs

### ISSUE THREAD

**Issue by emadb** [JakeBecker/vscode-elixir-ls#67]
Hope to be in the right repository.
What about using a different colors for @type and @spec directive?
Probably could just be a little bit darker than the function definition. I think it can improve readability.

Thank you.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
