### ISSUE TITLE
Shouldn't do: be highlighted in this context?

### ISSUE THREAD

**Issue by ijverig** [JakeBecker/vscode-elixir-ls#69]
`do` is correctly highlighted in a `do … end` block.
However, when we use its short version, `do` looses its color:

![screen shot 2018-04-27 at 14 38 10](https://user-images.githubusercontent.com/343219/39376703-fe5dbdc0-4a28-11e8-9e96-4973fa27618f.png)

It's then parsed as a named parameter (keyword list), which it is, but it's still the `do` block and IMHO should be highlighted as such.

Thoughts?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
