### ISSUE TITLE
Path mapping to support "Go to detention" inside Docker

### ISSUE THREAD

**Issue by iJackUA** [JakeBecker/vscode-elixir-ls#7]
Hi, this Extension and ElixirLS by itself looks very promising!

Previously I have started the same topic in VSCode-Elixir extension repo https://github.com/fr1zle/vscode-elixir/issues/59  (all details and my temporary solution is there).

Briefly: 
Is it possible somehow to specify path mapping between container FS and Host FS? (I suppose it should be a Workspace settings per project like mapping "${workspaceRoot} => /www")
Because when you develop locally using Docker containers, so Erlang/Elixir by itself and the source code are placed INSIDE the container. 
And `module.module_info[:compile][:source]` returns absolute path for container FS, but not for Host FS (that is expected by VSCode).
I suppose the same issue would arise not only for "go to definition" but for Debugger call stack source code display also.

I have a small repo with steps and expected / actual behavior https://github.com/iJackUA/vscode-elixir-docker-test

As I see this issue should be solved on both parts: VSCode extension should have path mapping param and pass it to Elixir server to do path normalization where `module_info` is done.

I understand that my request is not the main priority at such an early dev stage, but if you could just keep in mind this use case and eventually provide a solution for this - it would be awesome!

**Comment by JakeBecker** [comment]
This issue was moved to JakeBecker/elixir-ls#65
