### ISSUE TITLE
Windows10 WSL support

### ISSUE THREAD

**Issue by schlumpfling42** [JakeBecker/vscode-elixir-ls#71]
Would it possible to get the debugger running on Windows Subsystem for Linux?

**Comment by astutecat** [comment]
This would be of interest to me as well, what challenges are there in doing this?

**Comment by phpcitizen** [comment]
+1

**Comment by AlejandroHuerta** [comment]
Take a look at #16

**Comment by AlejandroHuerta** [comment]
This should now be possible with the new Remote Extensions feature in VSCode. You can run the elixirls extension in the wsl environment.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
