### ISSUE TITLE
Incremental dialyzer does not catch changes in remote types that fix a warning.

### ISSUE THREAD

**Issue by NobbZ** [JakeBecker/vscode-elixir-ls#72]
Given the files `a.ex` and `b.ex`, where in `b.ex` a type from `a.ex` is used in a spec.

But then there is a warning in because I am not using the type correctly. Therefore I alter the type defined in `a.ex`.

The warning in `b.ex` will persist until I `rm -rf .elixir_ls/dialyzer_*` and reload VScode.

start with

```
# a.ex
defmodule A do
  @type t :: %{}
end

# b.ex
defmodule B do
  @spec doit(A.t()) :: A.t()
  def doit(a), do: %{a | ok: true}
end
```

Get a warning at `B.doit/1`s `@spec`.

Fix `a.ex`:

```
defmodule A do
  @type t :: map()
end
```

But the warning in b.ex persists, even after restarts of VScode.

**Comment by JakeBecker** [comment]
This issue was moved to JakeBecker/elixir-ls#79
