### ISSUE TITLE
Formatter Issues with html.eex files 

### ISSUE THREAD

**Issue by AlmogRnD** [JakeBecker/vscode-elixir-ls#74]
I have the following set in my settings `"editor.formatOnSave":true`, which is great for pure ex-files ho every for my main HTML file it creates issues with JS and CSS imports attached gif showing the issue

This happens when I save  

![issue-1](https://user-images.githubusercontent.com/169507/40494360-02d6e2c4-5fb8-11e8-982c-93b864aa7861.gif)

**Comment by JakeBecker** [comment]
You can target specific languages in your settings like this:
```
"[elixir]": {
  "editor.formatOnSave": true
}
```

**Comment by AlmogRnD** [comment]
Thanks
