### ISSUE TITLE
Ability to copy variable values during debug to the clipboard?

### ISSUE THREAD

**Issue by bcardarella** [JakeBecker/vscode-elixir-ls#77]
<img width="269" alt="screen shot 2018-06-30 at 5 09 37 am" src="https://user-images.githubusercontent.com/18524/42123664-dd6468da-7c23-11e8-9891-bc86dec107c1.png">

When debugging the variable list has values that cannot be copied to the clipboard. Is there any reason why this is restricted? All options for the context menu are disabled. (as seen in the picture above)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
