### ISSUE TITLE
Ability to run single or groups of tests

### ISSUE THREAD

**Issue by bcardarella** [JakeBecker/vscode-elixir-ls#78]
It would be great if the debugger could allow us to run a single test rather than having to run the entire test suite again

**Comment by chulkilee** [comment]
Proposal: Find unit test based on file structure, and run it

- `lib/foo/bar.ex` => `test/foo/bar_test.exs`
- `apps/foo/lib/foo/bar.ex` => `apps/foo/test/foo/bar_test.exs`

As far as I know, there is no recommendation on structure inside test directory. Also you can put a file in arbitrary location under `lib`.

**Comment by chulkilee** [comment]
Okay, here is my first try

`.vscode/tasks.json`

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "group": "test",
      "label": "Run single test from open active file",
      "type": "shell",
      "command": "./.vscode/run-test.exs open_active_file ${workspaceRoot} ${file}"
    },
    {
      "group": "test",
      "label": "Run all tests",
      "type": "shell",
      "command": "./.vscode/run-test.exs all"
    }
  ]
}
```


`.vscode/run-test.exs`

```elixir
#! /usr/bin/env elixir

defmodule TestRunner do
  def run(["all"]), do: cmd("mix", ["test"])

  def run(["open_active_file", root_path, open_file]) do
    open_file = String.replace_prefix(open_file, root_path <> "/", "")

    case find_test_target(open_file) do
      :not_found ->
        IO.puts("could not find test file for #{open_file}")

      test_target ->
        args = build_test_command_args(test_target)
        IO.puts("mix #{Enum.join(args, " ")}")

        cmd("mix", args)
    end
  end

  defp cmd(command, args),
    do: System.cmd(command, args, into: IO.stream(:stdio, :line), stderr_to_stdout: true)

  defp find_test_target(path) do
    case Path.split(path) do
      ["apps" | [app_name | rest]] ->
        app_root = Path.join(["apps", app_name])
        path = Path.join(rest)

        case guess_test_file(app_root, path) do
          :not_found -> :not_found
          found -> {app_name, found}
        end

      _ ->
        guess_test_file("", path)
    end
  end

  defp guess_test_file(root, path) do
    if String.ends_with?(path, "_test.exs") do
      path
    else
      [file | parent_paths] = path |> Path.split() |> Enum.reverse()

      from_lib_path =
        parent_paths |> Enum.take_while(fn dir -> dir != "lib" end) |> Enum.reverse()

      test_file_name = String.replace_suffix(file, ".ex", "_test.exs")
      test_path = Path.join(["test" | from_lib_path] ++ [test_file_name])

      if root |> Path.join(test_path) |> File.exists?() do
        test_path
      else
        :not_found
      end
    end
  end

  defp build_test_command_args({app_name, path}),
    do: ["cmd", "--app", app_name, "mix", "test", path]

  defp build_test_command_args(path), do: ["test", path]
end

System.argv() |> TestRunner.run()
```

**Comment by michallepicki** [comment]
What I'm usually doing when debugging a single test is adding a unique tag to it and configuring the launch target `taskArgs` to restrict running tests to only this tag.

In `launch.json`:
```
"taskArgs": [
        "--only",
        "debug",
        "--trace"
      ]
```

In your `_test.exs` file:
```
  @tag :debug
  test "some test" do
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
