### ISSUE TITLE
.formatter.ex not respected

### ISSUE THREAD

**Issue by ZizhengTai** [JakeBecker/vscode-elixir-ls#82]
macOS: 10.13.5
VSCode: 1.25.0
ElixirLS: 0.2.19
Elixir: 1.6.6

In a Mix project where the `.formatter.exs` file looks like this:
```elixir
[
  inputs: []  # format nothing
]
```
If I mess with the format of say `mix.exs` and run `mix format` manually, I can confirm that `mix.exs` doesn't get reformatted. However, from within VSCode, both Alt+Shift+F and format-on-save will reformat `mix.exs`.

(On a side note, I'm observing the exact same behavior with [elixir-mode](https://github.com/elixir-editors/emacs-elixir) for Emacs. I don't think elixir-mode is backed by ElixirLS so that's weird. Could it be that the latest Elixir releases broke something for both of you?)

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
