### ISSUE TITLE
Support useCodeSnippetsOnMethodSuggest setting

### ISSUE THREAD

**Issue by ZizhengTai** [JakeBecker/vscode-elixir-ls#85]
Currently, when autocompleting a function, ElixirLS seems to always insert the parameter placeholders. Normally, I can jump to the next placeholder by pressing tab. But if I'm interrupted when filling some parameter (say there is an autocomplete suggestion that I rejected), tab doesn't go to the next placeholder anymore, and I'll have to manually select all remaining parameters one by one, which is annoying.

For some other languages (e.g. TypeScript, Go, etc.), this behavior is controlled by the `useCodeSnippetsOnMethodSuggest` setting. For example, when `typescript.useCodeSnippetsOnMethodSuggest == false`, only the function name will be inserted; when `useCodeSnippetsOnMethodSuggest == true`, both the function name and the parameter placeholders will be inserted.

Can ElixirLS support this option?

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
