### ISSUE TITLE
My System freezes when I fire up VScode having ElixirLS enabled. Kindly help.

### ISSUE THREAD

**Issue by rokfrog** [JakeBecker/vscode-elixir-ls#86]
I shared the same issue on stackoverflow. Just wanted to make sure if anyone face the same issue would be helpful.
https://stackoverflow.com/questions/51242190/how-to-setpath-for-system-wide-use-of-elixir-and-configuring-vscode-for-elixirls

When I open VSCode, with Elixir-Ls https://github.com/JakeBecker/vscode-elixir-ls plugin installed, my system just freezes. And I can't click anything. VSCode shows a pop up message as
 

>    "Failed to run "elixir" command ElixirLs will probably fail to launch

Kindly help with the installation path to set for usage and how to get ElixirLs working fine for Visual Studio. I even tried with "asdf" but didn't work for Vscode.

**Comment by JakeBecker** [comment]
Huh. The extension tries running the command `elixir -e ""` and checks whether the return code is 0 before running the extension. Try running that command and see what happens.

If it works, if you have Node installed, try this and see if it succeeds:
```
import { execSync } from "child_process";
execSync('elixir -e ""');
```

If that's uninformative, try launching VS Code from that CLI window to see if it's a problem with VS Code's PATH environment variable.

**Comment by NobbZ** [comment]
Also the freeze might be caused by the dialyzer run by the LS. Is there an easy way to deactivate it?

**Comment by rokfrog** [comment]
@JakeBecker  I'm unable to run the script

$ erl
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V9.3  (abort with ^G)
$ iex
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.6.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
$ nodejs 
> import { execSync } from "child_process";
... 
... execSync( 'elixir -e ""' );

And on the editor I am getting the popup as usual and it freezes the system
. "Failed to run 'elixir' command. ElixirLS will probably fail to launch."

**Comment by JakeBecker** [comment]
Sorry, I copied and pasted that from the extension without converting from Typescript syntax. It should actually be `require("child_process").execSync("elixir -e \"\"");`

But here's an easier way to check: Go to the "Terminal" tab in VS Code, and just type `elixir` and hit enter. My guess is that this will fail, which would indicate that VS Code isn't picking up your PATH environment variable correctly. Not sure how to fix that, though...

**Comment by NobbZ** [comment]
The terminal in VScode starts a login shell, so its corresponding RC files get evaluated.

If those RC files bring elixir into the PATH, then it might even work there but its still not discoverable by VScode.

Therefore, how is VScode started? From some Launcher or from a terminal? If the latter it should see the same PATH as the terminal does. Therefore if it gets started through a GUI usually, I'd give the terminal way a try (`code .` from within an elixir project).

To actually check the PATH that VScode sees, one should `CTRL-SHIFT-P`, "Developer: Toggle Developer Tools", in the apearing dev tools open the "console" tab and enter `process.env.PATH` there and check the output. Compare that with the PATH from a terminal that sees the elixir executable.

**Comment by rokfrog** [comment]
@JakeBecker 
```
 $ nodejs
> require("child_process").execSync("elixir -e \"\"");
<Buffer >
>
```
Inside the VScode terminal when I give the command elixir I'm getting this.
 $ elixir
Usage: elixir [options] [.exs file] [data]

  -e COMMAND                  Evaluates the given command (*)
  -r FILE                     Requires the given files/patterns (*)
  -S SCRIPT                   Finds and executes the given script in PATH
  -pr FILE                    Requires the given files/patterns in parallel (*)
  -pa PATH                    Prepends the given path to Erlang code path (*)
  -pz PATH                    Appends the given path to Erlang code path (*)

  --app APP                   Starts the given app and its dependencies (*)
  --cookie COOKIE             Sets a cookie for this distributed node
  --detached                  Starts the Erlang VM detached from console
  --erl SWITCHES              Switches to be passed down to Erlang (*)
  --help, -h                  Prints this message and exits
  --hidden                    Makes a hidden node
  --logger-otp-reports BOOL   Enables or disables OTP reporting
  --logger-sasl-reports BOOL  Enables or disables SASL reporting
  --name NAME                 Makes and assigns a name to the distributed node
  --no-halt                   Does not halt the Erlang VM after execution
  --sname NAME                Makes and assigns a short name to the distributed node
  --version, -v               Prints Elixir version and exits
  --werl                      Uses Erlang's Windows shell GUI (Windows only)

** Options marked with (*) can be given more than once
** Options given after the .exs file or -- are passed down to the executed code
** Options can be passed to the Erlang runtime using ELIXIR_ERL_OPTIONS or --erl


@NobbZ 
I can open VScode from terminal as well as from GUI.
And p

process.env.PATH
"/home/tesla/.exenv/shims:/home/tesla/.exenv/bin:/home/tesla/.exenv/shims:/home/tesla/.exenv/bin:/home/tesla/bin:/home/tesla/.local/bin:/home/tesla/.exenv/shims:/home/tesla/.exenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/tesla/.local/bin:/usr/local/go/bin:/bin:/home/tesla/.local/bin:/home/tesla/.local/bin:/home/tesla/go_projects/bin"
elixir

**Comment by bryanhuntesl** [comment]
@rokfrog - are you running ZSH as your login shell? I've had multiple problems with this before (variety of Erlang/Elixir applications).

**Comment by joaquinalcerro** [comment]
@NobbZ 

I have the same problem with the following:

```
-> which elixir
/home/jalcerro/.asdf/shims/elixir

process.env.PATH
"/home/jalcerro/.asdf/shims:/home/jalcerro/.asdf/shims:/home/jalcerro/.asdf/bin:/home/jalcerro/.nvm/versions/node/v6.13.0/bin:/home/jalcerro/.rvm/gems/ruby-2.6.3/bin:/home/jalcerro/.rvm/gems/ruby-2.6.3@global/bin:/home/jalcerro/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin:/home/jalcerro/.rvm/bin:/home/jalcerro/.rvm/bin"

```
I am able to run Elixir-LS from tty with "code ." command but when calling from i3 shortcut it fails.

When you say: "This is because most people only ever add something to the PATH via their shells RC-script, which is not evaluated by your GUI (unless you started X from a TTY)."

Where can I define the path that will be evaluated by GUI applications.

**Comment by NobbZ** [comment]
Depending on your system configuration you have some options.

If you use `pam_env` you can use `~/.pam_environment` (`man 8 pam_env` and `man 5 pam_env.conf`).

If you don't then you'll need to use either `~/.xinitrc` (Xorg) or `~/.config/environment.d/envvars.conf` (Wayland).

**Comment by saulimus** [comment]
I had the same error when using asdf to manage Elixir versions.
Found the solution for MacOS Mojave here:
https://apple.stackexchange.com/questions/57385/where-are-system-environment-variables-set-in-mountain-lion/146047#146047

In my case I made a script with:
`do shell script "launchctl setenv PATH \"$PATH;/Users/insertyourusernamehere/.asdf/shims\""`
Hope this helps someone with the same problem.

**Comment by jersearls** [comment]
I also had this issue once I started using ASDF, I was able to fix it by ensuring that I was sourcing the asdf.bash and shims as the LAST step of my `.profile`. You'll need to figure out the source order of your shell environment scripts and ensure that these are last. This fixed it for me. There is a note about it in the installation steps for ASDF. 

More info here: https://asdf-vm.com/#/core-manage-asdf-vm?id=having-issues

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!

**Comment by themgt** [comment]
FWIW I had this problem. I finally resolved it by editing `.vscode/extensions/jakebecker.elixir-ls-0.3.3/elixir-ls-release/launch.sh`

`asdf_vm="~/.asdf/asdf.sh"` => `asdf_vm="/usr/local/opt/asdf/asdf.sh"`

I realized the problem is because I installed asdf via homebrew rather than git, and apparently the vscode launch script assumes the `asdf.sh` will be where git install goes

**Comment by axelson** [comment]
@themgt another solution is to source your asdf setup in `~/.config/elixir_ls/setup.sh`:

https://github.com/elixir-lsp/elixir-ls/blob/5715d5274c8087057858427aac3090a6275cbe4c/README.md#local-setup
