### ISSUE TITLE
Triggering line comments in eex files

### ISSUE THREAD

**Issue by x-ji** [JakeBecker/vscode-elixir-ls#87]
Not sure if this relates more to this repo, vscode-elixir or elixir-ls. I'll just first open it here. Normally `Ctrl + /` should comment the line, and in `.eex` files the comment syntax is the same as in normal html files, unless it's a code statement, in which case one should use the Elixir comment syntax `#`.

In Emacs + Alchemist both types of comments can be triggered correctly. In some other editor/plugin combinations only the HTML one is triggered, which is fine most of the time. However in VSCode with `vscode-elixir-ls` currently neither seems to be triggered. This should be configurable? Manually starting HTML comment `<!-- -->` is quite inconvenient.

**Comment by crbelaus** [comment]
Should be fixed in #122

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
