### ISSUE TITLE
How to turn off wrapping long lines on save?

### ISSUE THREAD

**Issue by nathanchere** [JakeBecker/vscode-elixir-ls#89]
I don't care if it means I have to disable the format-on-save entirely, it's worth it to stop having long lines wrapped every time I save. I've only been able to disable it by disabling the entire extension and can't find any option either in documentation or in the packages.json to suggest a way of disabling it.

**Comment by adamvaughan** [comment]
Pretty sure the long line wrapping is done by the Elixir formatter, not this plugin. To keep the formatter from running when you save your file put `"editor.formatOnSave": false` in your user settings.

**Comment by doughsay** [comment]
@nathanchere the built in elixir formatter is separate from this plugin, you can invoke it by running `mix format`, which would also wrap your long lines.  You can configure the formatter for your project by adding a file in the root called `.formatter.exs` with contents something like this:

```elixir
# Used by "mix format"
[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 120
]
```

Change the `line_length` key to anything you want.

**Comment by nathanchere** [comment]
Between the two answers lies a complete solution to the problem, thank you both!
