### ISSUE TITLE
Use markdown language server for documentation

### ISSUE THREAD

**Issue by michalmuskala** [JakeBecker/vscode-elixir-ls#93]
As far as I'm aware, VSCode offers functionality that allows embedding one language inside another - for example PHP, CSS, and Javascript inside HTML.

It would be great, if the elixir extension recognised that documentation is written in markdown and used markdown syntax highlighting inside the docstrings.

I'm willing to work on this, but I'd need some pointers on how this could be achieved. I don't know anything about VSCode internals.

**Comment by ratbag98** [comment]
Happy to add another issue if needed, but in a related vein it would be great if SQL was spotted inside migrations (end elsewhere, though that might be trickier).

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
