### ISSUE TITLE
Formatter and Dialyzer not working

### ISSUE THREAD

**Issue by ghoetker** [JakeBecker/vscode-elixir-ls#94]
I installed the extension from inside of VS Code and, as the tile says, neither auto formatting (I enabled it in User Settings) nor manual (with Alt + Shift + F) works. Running Elixir 1.6.6 (compiled with OTP 21),  VSCode 1.25.1, on a MacOS 10.13.6 (High Sierra).  I saw closed issue #42, but unlike it, other aspects of the extension seem to be working, specifically code completion and documentation lookup on hover.  Please let me know if I can provide any additional information to help debug. Thank you.

**Comment by andrelip** [comment]
Please try this command and then restart vscode:
`rm -r deps _build .elixir_ls && mix deps.get`

**Comment by JakeBecker** [comment]
Please also go to `View > Output` and select "ElixirLS" in the dropdown, then post any parts of the log that look relevant.

**Comment by ghoetker** [comment]
Trying the provided command and restarting vscode made no difference (however, would you please specify in which directory it should be run, just so I can be sure I did exactly what you hoped I would do).

Relevant parts of the output log follow:

Started ElixirLS

[Error - 8:31:37 PM] Request textDocument/formatting failed.
  Message: an exception was raised:
    ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
        (elixir) lib/io.ex:461: IO.chardata_to_string(nil)
        (elixir) lib/path.ex:561: Path.split/1
        (elixir) lib/path.ex:313: Path.relative_to/2
        (language_server) lib/language_server/providers/formatting.ex:11: ElixirLS.LanguageServer.Providers.Formatting.format/3
        (language_server) lib/language_server/server.ex:412: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 
[Error - 8:31:37 PM] Process #PID<0.124.0> raised an exception
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:461: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:561: Path.split/1
    (elixir) lib/path.ex:313: Path.relative_to/2
    (language_server) lib/language_server/providers/formatting.ex:11: ElixirLS.LanguageServer.Providers.Formatting.format/3
    (language_server) lib/language_server/server.ex:412: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2

**Comment by bdubaut** [comment]
Hi, I am facing a somewhat similar issue. Dialyzer does not seem to be working with ElixirLS on VSCode 1.26.1 as I get the following alert message:

![screen shot 2018-08-27 at 09 29 59](https://user-images.githubusercontent.com/798319/44646585-ce5e0400-a9db-11e8-835a-da23b198ce8e.png)

When checking which version of Elixir I am running, here's what I get:

```
$> $(which elixir) -v
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.2 (compiled with Erlang/OTP 19)
```

I did try what @andrelip suggests, without success.

Any ideas?

**Comment by qqdanielqq** [comment]
@bdubaut Depending on which package manager you use you can recompile elixir via that, if you use `asdf` you can compile it with a different otp version by using the following command:
```
asdf install elixir 1.7.2-otp-{OTP VERSION YOU WANT HERE}
```

so for you it would be `asdf install elixir 1.7.2-otp-21`

**Comment by bdubaut** [comment]
Thanks @qqdanielqq I will try that. Although it works perfectly fine when using ElixirLS with Atom 🤔.

**Comment by alexmorral** [comment]
I'm having the same error.

The ElixirLS log on VSCode:

```
Started ElixirLS
Elixir version: "1.9.4 (compiled with Erlang/OTP 22)"
Erlang version: "22"
[Error - 11:53:24 AM] Request textDocument/formatting failed.
  Message: an exception was raised:
    ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
        (elixir) lib/io.ex:557: IO.chardata_to_string(nil)
        (elixir) lib/path.ex:566: Path.split/1
        (elixir) lib/path.ex:315: Path.relative_to/2
        (language_server) lib/language_server/providers/formatting.ex:11: ElixirLS.LanguageServer.Providers.Formatting.format/3
        (language_server) lib/language_server/server.ex:425: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
  Code: -32000 

11:53:24.978 [error] Process #PID<0.109.0> raised an exception
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:557: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:566: Path.split/1
    (elixir) lib/path.ex:315: Path.relative_to/2
    (language_server) lib/language_server/providers/formatting.ex:11: ElixirLS.LanguageServer.Providers.Formatting.format/3
    (language_server) lib/language_server/server.ex:425: anonymous fn/3 in ElixirLS.LanguageServer.Server.handle_request_async/2
```

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
