### ISSUE TITLE
"Debug adapter process has terminated unexpectedly"

### ISSUE THREAD

**Issue by pwightman** [JakeBecker/vscode-elixir-ls#96]
Hi! This isn't a proper issue (yet) but I could find any other forum to contact the maintainers. I've installed this plugin and it's working great, except that attempting to run anything from the Debug navigator (e.g. `mix test`) results in a "Debug adapter process has terminated unexpectedly" error pop-up in VSCode.

My issue is: there is no error information in any of VSCode's outputs that I can tell (e.g. `View -> Output` menu), so I'm not sure how to find information to diagnose the problem further. Any suggestions on where to look?

My environment is set up with `asdf` with the following `.tool-versions` file:

```
erlang 20.3
elixir 1.6.4-otp-20
nodejs 8.11.3
```

OS: Freshly installed macOS 10.13.6

That's the only thing I can think of that's "special" about my setup.

**Comment by JakeBecker** [comment]
Try running this from a terminal: `~/.vscode/extensions/jakebecker.elixir-ls-0.2.23/elixir-ls-release/debugger.sh`. Does it output anything?

**Comment by pwightman** [comment]
```
Content-Length: 113

{"body":{"category":"stdout","output":"Started ElixirLS debugger\n"},"event":"output","seq":1,"type":"event"}
```

**Comment by JakeBecker** [comment]
Ah. Well that unfortunately doesn't clear things up. VS Code's lack of information when the debug adapter crashes makes this hard to debug.

Go to `Help > Toggle Developer Tools` in VS Code. Any informative errors there?

**Comment by pwightman** [comment]
Ah, indeed there is.

![image](https://user-images.githubusercontent.com/838674/44163502-df745000-a080-11e8-91bf-f4e9a94ca33c.png)

It can't find `elixir`...but it appears the rest of the plugin is able to if autocomplete, etc, are working? Or do those not invoke `elixir`?

`/Users/parkerwightman/.asdf/shims/elixir` does run elixir properly FWIW.

**Comment by pwightman** [comment]
So I think the elixir executable missing is potentially a separate problem... I opened VSCode using `code .` inside my project directory and that error has gone away. Pressing the "Play" button in the debug menu now just produces this error.

![image](https://user-images.githubusercontent.com/838674/44164017-2747a700-a082-11e8-8548-63197be80bd1.png)

**Comment by JakeBecker** [comment]
In the "Output" panel, select "Extensions" from the dropdown and try launching the debugger. Any output there?

**Comment by pwightman** [comment]
No, no relevant output in any of the Output filters. Not sure if "Log (Extension Host)" is relevant but nothing there either. :-(

**Comment by pwightman** [comment]
This is the most relevant bit I've been able to find:

![image](https://user-images.githubusercontent.com/838674/44169126-bcea3300-a090-11e8-813a-e308d4dfc462.png)

126 exit code is "command found but is not executable"...permissions look right for it to be executable though:

```
-rwxr-xr-x  1 parkerwightman  staff     448 Aug 13 09:46 debugger.sh
```

May be a symptom of some other error. Running the command manually at the terminal works fine. Still digging...

**Comment by pwightman** [comment]
This has something to do with my own environment, setting `asdf`'s global erlang/elixir versions to my project version seems to have fixed it. Thanks! Sorry for the waste of time.
