### ISSUE TITLE
Start with --node and --cookie

### ISSUE THREAD

**Issue by cburman01** [JakeBecker/vscode-elixir-ls#97]
Is there support to run something similar? 

` iex --name bld_six@127.0.0.1 --cookie 123 -S mix boot app_2`

Here is my .vscode that will start the task boot, but i don't know how to start with a cookie and a node name. 
```
{
"type": "mix_task",
"name": "boot app_2",
"request": "launch",
"projectDir": "${workspaceRoot}",
"task": "boot",
"taskArgs": ["app_2"]
}

```

**Comment by mjaric** [comment]
I need this to, instead of auto generating node name so Elixir LS server can access app node, it would be good to expose in launch.json config distribution flags such as `name` or `sname` and `cookie` otherwise read ~/.erlang.cookie.

Second option is to respect when one is set env variable `ELIXIR_ERL_OPTIONS`

```
{
      "type": "mix_task",
      "name": "mix phx.server",
      "request": "launch",
      "projectDir": "${workspaceRoot}",
      "task": "phx.server",
      "startApps": true,
      "env":{
        "ELIXIR_ERL_OPTIONS": "-name someapp@127.0.0.1"
      }
    },
```

**Comment by s-ledenev** [comment]
No update on this issue? Seems to be that this plugin for Elixir is not so powerful as plugin for Erlang.

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!

**Comment by lukaszsamson** [comment]
Posting here since this issue was referenced in https://github.com/elixir-lsp/vscode-elixir-ls/issues/13 as original one.
`ELS_ELIXIR_OPTS` and `ELS_ERL_OPTS` are now supported. You can pass `--sname --cookie mycookie` via `ELS_ELIXIR_OPTS`. I believe this issue is now resolved.
