### ISSUE TITLE
Live reload not working when when launching mix task for phx.server

### ISSUE THREAD

**Issue by schlumpfling42** [JakeBecker/vscode-elixir-ls#98]
I setup a simple webapp with phoenix using vue with brunch. 
I can start it without issues with this launcher:
        {
            "type": "mix_task",
            "name": "mix (Default task)",
            "request": "launch",
            "task": "phx.server",
            "projectDir": "${workspaceRoot}"
        }
But as soon as I change a file (e.g. simpleApp_web\templates\page\index.html.eex) and it needs to recompile, I get the following error:
Compiling 1 file (.ex)
== Compilation error in file lib/simpleApp_web/views/page_view.ex ==
** (CompileError) lib/simpleApp_web/views/page_view.ex:2: module SimpleAppWeb is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/simpleApp_web/views/page_view.ex:2: SimpleAppWeb.PageView (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
Compiling 1 file (.ex)
== Compilation error in file lib/simpleApp_web/views/page_view.ex ==
** (CompileError) lib/simpleApp_web/views/page_view.ex:2: module SimpleAppWeb is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/simpleApp_web/views/page_view.ex:2: SimpleAppWeb.PageView (module)
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

If I start Phoenix from the command line, it works fine. Any ideas what the issue might be?
I'm using 
 Erlang/OTP 20 [erts-9.2] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10]
 Elixir 1.7.2 (compiled with Erlang/OTP 19)
 ElixirLS 0.2.23

**Comment by delameko** [comment]
This is what my task looks like:

    {
      "label": "Phoenix Server",
      "type": "shell",
      "command": "iex",
      "args": ["-S", "mix", "phx.server"],
      "options": {
        "cwd": "${workspaceRoot}"
      },
      "presentation": {
        "reveal": "always",
        "panel": "new"
      }
    }

**Comment by schlumpfling42** [comment]
Thank you. Will I be able to debug with this?

**Comment by JakeBecker** [comment]
Live reload is probably not going to work while debugging, unfortunately. Debugging requires loading modules using `:int.i/1`, and compilation involves a unloading and reloading modules, and getting the two to place nice with each other is going to be difficult enough that I'm not going to attempt it.

I'd recommend only launching Phoenix in the debugger when you actually want to set a breakpoint and otherwise launching it from the CLI.
