### ISSUE TITLE
Warning when add custom Mix task in project

### ISSUE THREAD

**Issue by 7sDream** [JakeBecker/vscode-elixir-ls#99]
1. create a project with mix
2. create folder `lib/mix/tasks`
3. add `start.ex` in `lib/mix/tasks` with content:

```elixir
defmodule Mix.Tasks.Start do
  use Mix.Task

  def run(_), do: "Hello World" |> IO.puts
end
```

Elixir Linter will show a warning on line 1: `[ElixirLS Dialyzer] Callback info about the 'Elixir.Mix.Task' behaviour is not available`

![warning](https://i.loli.net/2018/08/19/5b78459c4d882.png)

---

Append: After I follow [those steps on stackoverflow](https://stackoverflow.com/questions/51208388/how-to-fix-dialyzer-callback-info-about-the-behaviour-is-not-available), run `mix dialyzer` in shell don't show warnings anymore, but VS Code keep showing.

**Comment by doughsay** [comment]
Does ElixirLS not read the config from `mix.exs`?  I see that there is a config option provided for `dialyzerWarnOpts`, which allows for customizing which flags are used (which is also redundant information if read from `mix.exs`), but there's no option for specifying the `plt_add_apps` option as described above.

So for example, our mix.exs project function contains: `dialyzer: [flags: [:error_handling, :unmatched_returns, :underspecs], plt_add_apps: [:mix]]`.  Is all of this ignored by ElixirLS?  Do I need to add the same list of flags in the `dialyzerWarnOpts` option?  And then how do I add the mix PLT?

**Comment by iautom8things** [comment]
I know it's been a while since this has been opened.  Have any of y'all figured out a way to suppress this?

**Comment by StasD** [comment]
Solved with this setting:
`"elixirLS.dialyzerEnabled": false`
lol...

**Comment by JakeBecker** [comment]
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!
